"""
Roteiros Aulas 4, 5, 6, 7 — Intensivao Quant AI
python gerar_roteiros_parte2.py
"""
import os
from docx import Document
from docx.shared import Pt, RGBColor, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH

BASE = os.path.dirname(os.path.abspath(__file__))

def novo_doc(num, titulo):
    doc = Document()
    for s in doc.sections:
        s.top_margin = Cm(2.5); s.bottom_margin = Cm(2.5)
        s.left_margin = Cm(3.0); s.right_margin = Cm(2.5)
    p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run(f"INTENSIVAO QUANT AI — AULA {num}")
    r.font.size = Pt(11); r.font.bold = True; r.font.color.rgb = RGBColor(0xF5,0xA6,0x23)
    p2 = doc.add_paragraph(); p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r2 = p2.add_run(titulo); r2.font.size = Pt(20); r2.font.bold = True
    r2.font.color.rgb = RGBColor(0x0D,0x1B,0x3E)
    p3 = doc.add_paragraph(); p3.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r3 = p3.add_run("Roteiro completo — uso exclusivo do instrutor")
    r3.font.size = Pt(10); r3.font.italic = True; r3.font.color.rgb = RGBColor(0x88,0x88,0x88)
    doc.add_paragraph(); return doc

def h1(doc,t):
    p=doc.add_heading(level=1);p.clear();r=p.add_run(t)
    r.font.size=Pt(15);r.font.bold=True;r.font.color.rgb=RGBColor(0x0D,0x1B,0x3E)
def h2(doc,t):
    p=doc.add_heading(level=2);p.clear();r=p.add_run(t)
    r.font.size=Pt(13);r.font.bold=True;r.font.color.rgb=RGBColor(0x1A,0x6E,0xAE)
def fala(doc,t):
    p=doc.add_paragraph();p.paragraph_format.space_after=Pt(8)
    r=p.add_run(t);r.font.size=Pt(11);r.font.color.rgb=RGBColor(0x1A,0x1A,0x1A)
def acao(doc,t):
    p=doc.add_paragraph();r=p.add_run(f"[{t}]")
    r.font.size=Pt(10);r.font.italic=True;r.font.color.rgb=RGBColor(0x88,0x44,0x00)
def cod(doc,t):
    p=doc.add_paragraph();p.paragraph_format.left_indent=Inches(0.4)
    r=p.add_run(t);r.font.name='Courier New';r.font.size=Pt(10)
    r.font.color.rgb=RGBColor(0x1A,0x6E,0xAE)
def tempo(doc,t):
    p=doc.add_paragraph();r=p.add_run(f"  {t}")
    r.font.size=Pt(9);r.font.bold=True;r.font.color.rgb=RGBColor(0xF5,0xA6,0x23)
def div(doc):
    p=doc.add_paragraph();r=p.add_run("─"*70)
    r.font.size=Pt(8);r.font.color.rgb=RGBColor(0xCC,0xCC,0xCC)


# ══════════════════════════════════════════════════════════════
# AULA 04 — SINAL v1
# ══════════════════════════════════════════════════════════════
def aula04():
    doc = novo_doc("04", "Sinal v1: Momentum Cross-Sectional")

    h1(doc, "ABERTURA")
    tempo(doc, "0:00 – 0:03")
    div(doc)
    fala(doc, "Bem-vindos a Aula 4. Ate agora a gente coletou e limpou os dados, explorou a distribuicao dos retornos. Hoje e o momento que tudo comeca a tomar forma: vamos construir o primeiro sinal quantitativo da estrategia — o momentum cross-sectional 12-1.")
    fala(doc, "Quando eu falo 'sinal', estou falando de um numero que calculamos para cada acao em cada data, que nos diz: compre essa acao ou nao. E mais especificamente, qual o ranking dessa acao em relacao as outras no mesmo periodo. O sinal transforma dados brutos em decisao de investimento.")

    div(doc)
    h1(doc, "PARTE 1 — TEORIA (25 min)")
    tempo(doc, "0:03 – 0:20")
    div(doc)

    acao(doc, "Avancar slide 3: O que e um Fator Quantitativo")
    h2(doc, "Do Dado ao Sinal ao Portfolio")
    fala(doc, "Um fator quantitativo e uma caracteristica mensuravel de um ativo que, baseada em teoria economica e evidencia empirica, prediz o retorno futuro daquele ativo. O momentum e um fator — e o nosso fator.")
    fala(doc, "O pipeline e sempre o mesmo: primeiro voce tem uma hipotese economica — no nosso caso, que acoes com bom retorno recente vao continuar performando bem no proximo mes. Depois voce transforma essa hipotese num sinal computavel — o retorno acumulado dos ultimos 12-1 meses. Depois voce usa o sinal para ranquear as acoes — e seleciona as melhores. E finalmente voce determina o peso de cada acao no portfolio.")
    fala(doc, "Cada passo desse pipeline e uma decisao que precisa de justificativa. Por que 12 meses? Por que excluir o ultimo? Por que top 10? Por que equal-weight? Vamos responder todas essas perguntas ao longo das proximas aulas — e ao final voces conseguem defender cada uma delas.")

    acao(doc, "Avancar slide 4: O Sinal 12-1")
    h2(doc, "O Sinal 12-1 — Formula e Intuicao")
    fala(doc, "O sinal de momentum 12-1 e definido assim: para cada acao, em cada mes t, calculamos o retorno acumulado dos meses t-12 ate t-2. Excluimos o mes t-1 — o mais recente.")
    fala(doc, "Em pandas, isso se escreve assim:")
    fala(doc, "ret_mensais.shift(2).rolling(11).sum()")
    fala(doc, "Vamos dissecar essa linha. O shift(2) desloca os dados dois periodos para frente no tempo. Isso significa que o que era o mes t agora aparece como t+2. O efeito pratico: quando calculamos em t, estamos usando dados de ate t-2. O rolling(11) calcula a janela movel de 11 meses. Resultado: retorno acumulado de 11 meses, comeando de t-12 e terminando em t-2 — que e exatamente o sinal 12-1.")
    fala(doc, "Por que o shift(2) e nao shift(1)? Aqui tem um detalhe critico. Precisamos de dois shifts: um para o skip do mes mais recente — que e onde mora a reversao de curto prazo — e um para o look-ahead bias. Se eu tivesse so shift(1), o retorno do mes t-1 seria calculado com o fechamento de t-1, que ja seria informacao disponivel so no inicio de t — e a gente executaria o trade no inicio de t. Na pratica, com dados de fechamento mensal, o shift(2) e o correto e conservador.")
    fala(doc, "Por que excluir o ultimo mes? Porque Jegadeesh documentou em 1990 — em um paper separado do famoso de 1993 — que o mes mais recente tem um efeito de reversao. Acoes que subiram muito no mes passado tendem a cair um pouco no mes seguinte. Isso e causado por microestrutura de mercado: bid-ask bounce, liquidez momentanea, portfolio rebalancing institucional no final do mes. Incluir esse mes no sinal degrada a performance.")

    acao(doc, "Avancar slide 5: Information Coefficient")
    h2(doc, "Information Coefficient — Medindo a Qualidade do Sinal")
    fala(doc, "Antes de backtester um sinal, vale a pena medir se ele tem poder preditivo. A metrica que usamos e o Information Coefficient — IC.")
    fala(doc, "O IC e a correlacao de Spearman entre o ranking do sinal em t e o ranking do retorno realizado em t+1. Spearman — e nao Pearson — porque a gente esta interessado em rankings, e queremos que a metrica seja robusta a outliers.")
    fala(doc, "Interpretacao: IC positivo significa que, em media, acoes com sinal alto tendem a ter retornos maiores no proximo mes. IC de 0 significa o sinal e randomico. IC negativo significa que o sinal preve o lado errado.")
    fala(doc, "Um IC medio de 0.05 — 5% — ja e considerado util na pratica quantitativa. Parece pequeno, mas pense assim: um toss de moeda tem IC de 0. Se voce tem um sinal com IC de 0.05, ao longo de muitos periodos, o efeito composto e substancial.")
    fala(doc, "Tambem calculamos o t-stat do IC: IC_medio dividido por (IC_desvio_padrao dividido pela raiz de N). Se o t-stat for maior que 2, o IC e estatisticamente significativo ao nivel de 5%.")

    div(doc)
    h1(doc, "PARTE 2 — LIVE CODING (40 min)")
    tempo(doc, "0:20 – 0:55")
    div(doc)

    acao(doc, "Abrir notebook: aulas/aula-04-sinal-v1/aula-04-sinal-v1.ipynb")

    h2(doc, "Bloco 1 — Importacoes e Dados")
    cod(doc, "import pandas as pd")
    cod(doc, "import numpy as np")
    cod(doc, "import matplotlib.pyplot as plt")
    cod(doc, "import seaborn as sns")
    cod(doc, "from scipy import stats")
    cod(doc, "")
    cod(doc, "ret_mensais = pd.read_parquet('../../dados/retornos_mensais_limpo.parquet')")
    cod(doc, "print('Shape:', ret_mensais.shape)")
    cod(doc, "print('Periodo:', ret_mensais.index[0].date(), 'a', ret_mensais.index[-1].date())")

    h2(doc, "Bloco 2 — Calcular o Sinal v1")
    fala(doc, "Agora a linha mais importante do intensivao. A gente vai digitar ela devagar.")
    cod(doc, "# O sinal momentum 12-1")
    cod(doc, "# shift(2): exclui o mes mais recente (skip) e evita look-ahead")
    cod(doc, "# rolling(11): janela de 11 meses = sinal 12-1")
    cod(doc, "sinal_v1 = ret_mensais.shift(2).rolling(11).sum()")
    cod(doc, "")
    cod(doc, "print(f'Shape do sinal: {sinal_v1.shape}')")
    cod(doc, "print(f'Primeiros valores nao-nulos a partir de: {sinal_v1.dropna(how=\"all\").index[0].date()}')")
    cod(doc, "sinal_v1.tail(3)")
    fala(doc, "Reparem que as primeiras linhas sao NaN — isso e esperado. Precisamos de pelo menos 13 meses de retornos historicos para calcular o primeiro sinal: 11 meses de janela mais 2 de shift. Por isso coletamos dados a partir de 2012 mesmo que o backtest comece em 2014.")
    fala(doc, "Cada celula do DataFrame sinal_v1 e o retorno acumulado de 11 meses — com skip de 1 — para aquela acao naquele mes. O valor em PETR4 em dezembro de 2023, por exemplo, seria o retorno acumulado de PETR4 de novembro de 2022 ate outubro de 2023.")

    h2(doc, "Bloco 3 — Ranking Cross-Sectional")
    fala(doc, "Agora transformamos o sinal em ranking. Em cada mes, queremos saber: qual e a posicao relativa de cada acao dentro do universo?")
    cod(doc, "# Ranking percentual: 1.0 = melhor sinal, 0.0 = pior")
    cod(doc, "ranking = sinal_v1.rank(axis=1, pct=True, ascending=True)")
    cod(doc, "")
    cod(doc, "# Verificar: em cada mes, distribuicao dos rankings deve ser uniforme")
    cod(doc, "print('Distribuicao dos rankings em um mes exemplo:')")
    cod(doc, "print(ranking.dropna(how='all').iloc[-1].describe())")
    fala(doc, "O rank(axis=1) rankeia em cada linha — ou seja, em cada mes, compara todas as acoes entre si. O pct=True converte para escala 0-1, onde 1 e a acao com maior sinal e 0 e a com menor. ascending=True faz com que retorno maior vire ranking maior — e e o que queremos, porque queremos comprar as que mais subiram.")

    h2(doc, "Bloco 4 — Calcular o IC")
    fala(doc, "Agora medimos a qualidade do sinal com o Information Coefficient.")
    cod(doc, "from scipy.stats import spearmanr")
    cod(doc, "")
    cod(doc, "def calcular_ic_serie(sinal, retornos_futuros):")
    cod(doc, "    '''IC = Spearman(sinal_t, retorno_{t+1}) para cada t'''")
    cod(doc, "    ret_futuro = retornos_futuros.shift(-1)  # retorno do proximo mes")
    cod(doc, "    ic_list = []")
    cod(doc, "    for data in sinal.index:")
    cod(doc, "        s = sinal.loc[data].dropna()")
    cod(doc, "        r = ret_futuro.loc[data].reindex(s.index).dropna()")
    cod(doc, "        s_alinhado = s.reindex(r.index)")
    cod(doc, "        if len(r) >= 10:  # minimo de 10 acoes para calcular")
    cod(doc, "            ic, _ = spearmanr(s_alinhado, r)")
    cod(doc, "            ic_list.append({'data': data, 'ic': ic})")
    cod(doc, "    return pd.DataFrame(ic_list).set_index('data')['ic']")
    cod(doc, "")
    cod(doc, "ic_serie = calcular_ic_serie(sinal_v1, ret_mensais)")
    cod(doc, "")
    cod(doc, "ic_medio = ic_serie.mean()")
    cod(doc, "ic_std   = ic_serie.std()")
    cod(doc, "ic_tstat = ic_medio / (ic_std / np.sqrt(len(ic_serie)))")
    cod(doc, "ic_hit   = (ic_serie > 0).mean()")
    cod(doc, "")
    cod(doc, "print(f'IC Medio:  {ic_medio:.4f}')")
    cod(doc, "print(f'IC Std:    {ic_std:.4f}')")
    cod(doc, "print(f'IC t-stat: {ic_tstat:.2f}')")
    cod(doc, "print(f'Hit Rate:  {ic_hit:.1%}  (% de meses com IC > 0)')")
    fala(doc, "O que espero ver: IC medio positivo — provavelmente entre 0.02 e 0.08. t-stat acima de 2 indica significancia estatistica. Hit rate acima de 55% e bom — significa que na maioria dos meses o sinal acertou a direcao.")
    fala(doc, "Se o IC for negativo ou o t-stat for abaixo de 1.5, e preciso investigar antes de continuar. Pode ser um problema na implementacao do sinal — verifiquem se o shift esta correto.")

    h2(doc, "Bloco 5 — Visualizar o IC")
    cod(doc, "fig, axes = plt.subplots(2, 1, figsize=(14, 8))")
    cod(doc, "")
    cod(doc, "# Serie temporal do IC")
    cod(doc, "axes[0].bar(ic_serie.index, ic_serie, color=['g' if x>0 else 'r' for x in ic_serie],")
    cod(doc, "            alpha=0.7, width=20)")
    cod(doc, "axes[0].axhline(ic_medio, color='navy', ls='--', lw=2, label=f'Media: {ic_medio:.3f}')")
    cod(doc, "axes[0].set_title('Information Coefficient Mensal — Sinal v1')")
    cod(doc, "axes[0].legend()")
    cod(doc, "")
    cod(doc, "# IC movel de 12 meses")
    cod(doc, "ic_movel = ic_serie.rolling(12).mean()")
    cod(doc, "axes[1].plot(ic_movel, color='navy', lw=2)")
    cod(doc, "axes[1].axhline(0, color='gray', ls='-', lw=0.5)")
    cod(doc, "axes[1].fill_between(ic_movel.index, ic_movel, 0,")
    cod(doc, "                     where=ic_movel>0, alpha=0.3, color='green')")
    cod(doc, "axes[1].fill_between(ic_movel.index, ic_movel, 0,")
    cod(doc, "                     where=ic_movel<0, alpha=0.3, color='red')")
    cod(doc, "axes[1].set_title('IC Movel 12 meses')")
    cod(doc, "plt.tight_layout(); plt.savefig('ic_sinal_v1.png', dpi=150); plt.show()")
    fala(doc, "O que voces vao ver: barras verdes e vermelhas alternadas no primeiro grafico — nao existe sinal que acerta todo mes. Mas a media deve ser claramente positiva. No grafico de IC movel, voces podem identificar periodos em que o sinal funcionou melhor e pior — provavelmente correlacionado com o regime de mercado.")

    h2(doc, "Bloco 6 — Salvar o Sinal")
    cod(doc, "sinal_v1.to_parquet('../../dados/sinal_v1.parquet')")
    cod(doc, "print('sinal_v1.parquet salvo.')")
    cod(doc, "print(f'Shape: {sinal_v1.shape}')")
    cod(doc, "print(f'Periodo util (sem NaN): {sinal_v1.dropna(how=\"all\").index[0].date()} a {sinal_v1.index[-1].date()}')")
    fala(doc, "Perfeito. O sinal esta salvo. Na proxima aula, vamos usar esse sinal para construir o primeiro portfolio e calcular as metricas de performance.")

    div(doc)
    h1(doc, "FECHAMENTO DA AULA 4")
    tempo(doc, "1:55 – 2:00")
    div(doc)
    fala(doc, "Hoje construimos o sinal v1 — o momentum 12-1. Medimos que ele tem poder preditivo: IC positivo e estatisticamente significativo. Na Aula 5 vamos transformar esse sinal em portfolio e calcular as metricas completas de performance.")

    pasta = os.path.join(BASE, "aula-04-sinal-v1")
    doc.save(os.path.join(pasta, "roteiro-aula-04-sinal-v1.docx"))
    print("  Aula 04: roteiro salvo -> aula-04-sinal-v1/")


# ══════════════════════════════════════════════════════════════
# AULA 05 — BACKTEST v1
# ══════════════════════════════════════════════════════════════
def aula05():
    doc = novo_doc("05", "Backtest v1: Primeira Simulacao Historica")

    h1(doc, "ABERTURA")
    tempo(doc, "0:00 – 0:05")
    div(doc)
    fala(doc, "Bem-vindos a Aula 5. Chegamos em um marco do intensivao: hoje vamos rodar o primeiro backtest completo. Vamos pegar o sinal que construimos na Aula 4, transformar em portfolio e medir a performance historica pela primeira vez.")
    fala(doc, "Quero deixar algo muito claro antes de comecar: o resultado do backtest de hoje vai ser otimista. A gente ainda nao modelou custos, ainda nao fizemos walk-forward, ainda nao corrigimos todos os problemas de rigor. Isso vem na Aula 8. Por enquanto, estamos construindo a base — um backtest simples mas correto nas hipoteses que declaramos.")

    div(doc)
    h1(doc, "PARTE 1 — TEORIA (20 min)")
    tempo(doc, "0:03 – 0:20")
    div(doc)

    acao(doc, "Avancar slide 3: Hipoteses do Backtest")
    h2(doc, "O que Assumimos no Backtest")
    fala(doc, "Todo backtest e uma simulacao — uma aproximacao da realidade. O que diferencia um bom backtest de um ruim nao e ausencia de hipoteses simplificadoras — todas as simulacoes tem. O que diferencia e a transparencia sobre essas hipoteses.")
    fala(doc, "As hipoteses que estamos fazendo hoje: primeiro, execucao no fechamento do mes, sem slippage. Na vida real, quando voce executa uma ordem grande, o preco muda antes que voce termine de executar — isso e o market impact. Nos estamos ignorando isso.")
    fala(doc, "Segundo: liquidez ilimitada. Estamos assumindo que podemos comprar ou vender qualquer quantidade de qualquer acao ao preco de fechamento. Em pratica, acoes menos liquidas tem bid-ask spread maior e nao absorvem ordens grandes sem mover o preco.")
    fala(doc, "Terceiro: sem custos de transacao. Sem corretagem, sem taxa da B3, sem imposto. Isso vai ser corrigido na Aula 8 — mas por agora queremos ver o alpha bruto antes dos custos.")
    fala(doc, "Quarto: nao ha restricoes de posicao. Podemos ter qualquer fracao do portfolio em qualquer acao.")
    fala(doc, "Essas hipoteses fazem o backtest mais otimista do que a realidade. E e por isso que o juri vai perguntar sobre elas. A resposta certa nao e 'nao temos essas hipoteses' — e 'temos essas hipoteses e aqui esta o impacto estimado de cada uma'.")

    acao(doc, "Avancar slide 4: Metricas de Performance")
    h2(doc, "Metricas de Performance")
    fala(doc, "Existem muitas metricas de performance. Eu quero que voces entendam profundamente quatro delas — porque o juri vai perguntar sobre todas.")
    fala(doc, "O Sharpe Ratio, desenvolvido por William Sharpe em 1994, e a medida mais famosa. Formula: retorno medio em excesso sobre o risk-free, dividido pelo desvio padrao dos retornos, multiplicado pela raiz de 12 para anualizar. Ele mede: quantas unidades de retorno eu gero por unidade de risco total?")
    fala(doc, "A limitacao do Sharpe e que ele penaliza tanto retornos acima quanto abaixo da media — ele nao diferencia volatilidade de alta e volatilidade de baixa. Para uma estrategia long-only em acoes, com retornos assimetricos, isso pode ser injusto.")
    fala(doc, "O Sortino Ratio corrige isso. Em vez de dividir pelo desvio padrao total, dividimos pelo downside deviation — o desvio padrao calculado apenas sobre os retornos negativos. Um Sortino alto significa: a estrategia tem bom retorno por unidade de risco de perda.")
    fala(doc, "O Max Drawdown e a pior queda pico-a-vale no periodo. Se o portfolio chegou a 100, depois caiu para 75, isso e um drawdown de 25%. O Max Drawdown captura o pior cenario que um investidor real teria vivenciado. E critico porque e o que determina se um investidor consegue manter a estrategia — ou entra em panico e sai no pior momento.")
    fala(doc, "O Calmar Ratio e o CAGR dividido pelo valor absoluto do Max Drawdown. Ele responde: quanto de retorno anualizado eu gero por unidade de drawdown maximo? Um Calmar acima de 1 significa que o retorno anualizado e maior que o pior drawdown — isso e considerado bom.")

    div(doc)
    h1(doc, "PARTE 2 — LIVE CODING (40 min)")
    tempo(doc, "0:20 – 0:55")
    div(doc)

    acao(doc, "Abrir notebook: aulas/aula-05-backtest-v1/aula-05-backtest-v1.ipynb")

    h2(doc, "Bloco 1 — Carregar Dados e Sinal")
    cod(doc, "import pandas as pd")
    cod(doc, "import numpy as np")
    cod(doc, "import matplotlib.pyplot as plt")
    cod(doc, "from scipy import stats")
    cod(doc, "")
    cod(doc, "ret_mensais = pd.read_parquet('../../dados/retornos_mensais_limpo.parquet')")
    cod(doc, "sinal_v1    = pd.read_parquet('../../dados/sinal_v1.parquet')")

    h2(doc, "Bloco 2 — Construir Portfolio Equal-Weight")
    fala(doc, "A logica de construcao do portfolio e simples: em cada mes, identificar as top 10 acoes por sinal e dar peso igual de 10% para cada uma.")
    cod(doc, "def construir_portfolio(sinal, ret_mensais, n_top=10):")
    cod(doc, "    '''Constroi portfolio equal-weight com top N acoes por sinal'''")
    cod(doc, "    pesos = pd.DataFrame(0.0, index=sinal.index, columns=sinal.columns)")
    cod(doc, "    ")
    cod(doc, "    for data in sinal.index:")
    cod(doc, "        s = sinal.loc[data].dropna()")
    cod(doc, "        if len(s) >= n_top:")
    cod(doc, "            top = s.nlargest(n_top).index")
    cod(doc, "            pesos.loc[data, top] = 1.0 / n_top")
    cod(doc, "    ")
    cod(doc, "    # Retorno do portfolio: soma ponderada dos retornos")
    cod(doc, "    # Alinhando: pesos de t aplicados aos retornos de t+1")
    cod(doc, "    ret_portfolio = (pesos.shift(1) * ret_mensais).sum(axis=1)")
    cod(doc, "    ret_portfolio = ret_portfolio[ret_portfolio != 0]")
    cod(doc, "    ")
    cod(doc, "    return pesos, ret_portfolio")
    fala(doc, "Parem aqui — tem um detalhe critico. Usamos pesos.shift(1) na linha de calculo do retorno. Por que? Porque os pesos sao calculados no final do mes t usando o sinal formado em t. Mas o retorno que esses pesos geram e o retorno do mes t+1 — o mes seguinte ao rebalanceamento. O shift(1) garante esse alinhamento temporal correto.")
    fala(doc, "Se voce nao fizer o shift, voce esta usando os pesos do mes t para capturar o retorno do mes t, o que implicaria que voce sabe o sinal antes de tomar a decisao. E um look-ahead bias mais sutil que o do sinal em si, mas igualmente invalidante.")
    cod(doc, "pesos_v1, ret_v1 = construir_portfolio(sinal_v1, ret_mensais, n_top=10)")
    cod(doc, "print(f'Retornos do portfolio: {len(ret_v1)} meses')")
    cod(doc, "print(f'Periodo: {ret_v1.index[0].date()} a {ret_v1.index[-1].date()}')")

    h2(doc, "Bloco 3 — Funcao calcular_metricas")
    fala(doc, "Agora vamos criar a funcao mais reutilizada do intensivao. Essa funcao vai aparecer em todas as aulas de Aula 5 em diante.")
    cod(doc, "def calcular_metricas(retornos, benchmark=None, nome='Estrategia', rf_mensal=0.0):")
    cod(doc, "    r = retornos.dropna()")
    cod(doc, "    excesso = r - rf_mensal")
    cod(doc, "    n = len(r)")
    cod(doc, "    ")
    cod(doc, "    # Retorno e risco")
    cod(doc, "    cagr = (1 + r).prod() ** (12 / n) - 1")
    cod(doc, "    vol  = r.std() * np.sqrt(12)")
    cod(doc, "    ")
    cod(doc, "    # Sharpe e Sortino")
    cod(doc, "    sharpe  = (excesso.mean() / excesso.std()) * np.sqrt(12) if excesso.std() > 0 else np.nan")
    cod(doc, "    downside = excesso[excesso < 0].std() * np.sqrt(12)")
    cod(doc, "    sortino  = (excesso.mean() * 12 / downside) if downside > 0 else np.nan")
    cod(doc, "    ")
    cod(doc, "    # Drawdown")
    cod(doc, "    cum = (1 + r).cumprod()")
    cod(doc, "    dd  = cum / cum.cummax() - 1")
    cod(doc, "    mdd = dd.min()")
    cod(doc, "    calmar = cagr / abs(mdd) if mdd != 0 else np.nan")
    cod(doc, "    ")
    cod(doc, "    # Alpha e Beta vs benchmark")
    cod(doc, "    alpha, beta = np.nan, np.nan")
    cod(doc, "    if benchmark is not None:")
    cod(doc, "        b  = benchmark.reindex(r.index).dropna()")
    cod(doc, "        r2 = r.reindex(b.index)")
    cod(doc, "        if len(r2) > 10:")
    cod(doc, "            beta, intercept, *_ = stats.linregress(b.values, r2.values)")
    cod(doc, "            alpha = intercept * 12")
    cod(doc, "    ")
    cod(doc, "    return dict(nome=nome, cagr=cagr, vol=vol, sharpe=sharpe,")
    cod(doc, "                sortino=sortino, max_drawdown=mdd, calmar=calmar,")
    cod(doc, "                alpha=alpha, beta=beta, n_meses=n)")
    fala(doc, "Cada linha dessa funcao merece atencao. O CAGR usa prod() — multiplicacao de todos os fatores (1+r) — e depois eleva a 12/n para anualizar. Isso e o retorno composto anualizado correto.")
    fala(doc, "O Sharpe usa excesso.std() — o desvio padrao dos retornos em excesso — nao o desvio padrao simples. A diferenca e pequena quando rf e estavel, mas e conceitualmente correto.")
    fala(doc, "Para o drawdown, calculamos o cumsum de (1+r) — a curva de riqueza — e depois dividimos pelo cummax — o pico historico ate cada ponto. A diferenca e o drawdown. O minimo dessa serie e o Max Drawdown.")
    fala(doc, "O alpha e o intercept da regressao linear do retorno da estrategia contra o benchmark, multiplicado por 12 para anualizar. Ele representa o retorno medio da estrategia que nao e explicado pelo movimento do benchmark.")

    h2(doc, "Bloco 4 — Benchmark IBOVESPA")
    fala(doc, "Para comparar nossa estrategia, precisamos do retorno do IBOVESPA. Vamos usar o ticker ^BVSP ou o ETF BOVA11.SA como proxy.")
    cod(doc, "# IBOVESPA como benchmark")
    cod(doc, "# Opcao 1: usar ^BVSP direto do yfinance")
    cod(doc, "# Opcao 2: calcular retorno medio igualmente ponderado do universo")
    cod(doc, "# Usamos a opcao 2 para consistencia interna")
    cod(doc, "ret_ibov_proxy = ret_mensais.mean(axis=1)  # media igualmente ponderada")
    cod(doc, "ret_ibov_proxy.name = 'IBOV_proxy'")
    fala(doc, "Usar a media igualmente ponderada do nosso universo como benchmark tem uma vantagem: e construido com os mesmos dados e no mesmo periodo. A desvantagem e que nao reflete o IBOVESPA real, que e ponderado por liquidez.")
    fala(doc, "Para o relatorio final, recomendo baixar o retorno real do IBOVESPA via yfinance e usar como benchmark. Mas para analise interna, essa proxy serve muito bem.")

    h2(doc, "Bloco 5 — Calcular e Exibir Metricas")
    cod(doc, "def exibir_metricas(*dicts):")
    cod(doc, "    df = pd.DataFrame(dicts).set_index('nome')")
    cod(doc, "    formatos = {")
    cod(doc, "        'cagr':         '{:.1%}',")
    cod(doc, "        'vol':          '{:.1%}',")
    cod(doc, "        'sharpe':       '{:.2f}',")
    cod(doc, "        'sortino':      '{:.2f}',")
    cod(doc, "        'max_drawdown': '{:.1%}',")
    cod(doc, "        'calmar':       '{:.2f}',")
    cod(doc, "        'alpha':        '{:.1%}',")
    cod(doc, "        'beta':         '{:.2f}',")
    cod(doc, "    }")
    cod(doc, "    for col, fmt in formatos.items():")
    cod(doc, "        if col in df.columns:")
    cod(doc, "            df[col] = df[col].apply(lambda x: fmt.format(x) if pd.notna(x) else 'N/A')")
    cod(doc, "    return df")
    cod(doc, "")
    cod(doc, "m_v1   = calcular_metricas(ret_v1, ret_ibov_proxy, 'Momentum v1')")
    cod(doc, "m_ibov = calcular_metricas(ret_ibov_proxy, nome='IBOV Proxy')")
    cod(doc, "")
    cod(doc, "exibir_metricas(m_v1, m_ibov)")
    fala(doc, "Agora o momento da verdade. O que voces vao ver: a estrategia momentum deve ter Sharpe maior que o benchmark, CAGR maior, e Max Drawdown menor ou similar. Se isso nao aparecer, ha um problema na implementacao — verifiquem o sinal e a construcao do portfolio.")
    fala(doc, "Um resultado tipico para esse periodo no Brasil: Sharpe da estrategia de 0.7 a 1.1, Sharpe do benchmark de 0.3 a 0.6. Lembrem: esses numeros sao sem custos, entao sao otimistas.")

    h2(doc, "Bloco 6 — Graficos de Performance")
    cod(doc, "fig, axes = plt.subplots(2, 1, figsize=(14, 10))")
    cod(doc, "")
    cod(doc, "# Retorno acumulado")
    cod(doc, "ax = axes[0]")
    cod(doc, "cum_v1   = (1 + ret_v1).cumprod()")
    cod(doc, "cum_ibov = (1 + ret_ibov_proxy.reindex(ret_v1.index)).cumprod()")
    cod(doc, "ax.plot(cum_v1,   label='Momentum v1', lw=2, color='navy')")
    cod(doc, "ax.plot(cum_ibov, label='IBOV Proxy',  lw=1.5, color='gray', ls='--')")
    cod(doc, "ax.set_title('Retorno Acumulado — Momentum v1 vs IBOVESPA')")
    cod(doc, "ax.set_ylabel('Fator de crescimento (R$ 1 inicial)')")
    cod(doc, "ax.legend(); ax.grid(alpha=0.3)")
    cod(doc, "")
    cod(doc, "# Drawdown")
    cod(doc, "ax2 = axes[1]")
    cod(doc, "dd_v1 = cum_v1 / cum_v1.cummax() - 1")
    cod(doc, "ax2.fill_between(dd_v1.index, dd_v1, 0, color='red', alpha=0.5)")
    cod(doc, "ax2.set_title('Drawdown — Momentum v1')")
    cod(doc, "ax2.set_ylabel('Drawdown'); ax2.grid(alpha=0.3)")
    cod(doc, "plt.tight_layout(); plt.savefig('backtest_v1.png', dpi=150); plt.show()")
    fala(doc, "O grafico de retorno acumulado e o mais intuitivo para o juri e para voces. Uma curva que sobe acima do benchmark de forma consistente e o que buscamos. Quedas temporarias sao normais — o que importa e a tendencia de longo prazo e a recuperacao.")
    fala(doc, "O grafico de drawdown mostra quando e por quanto o portfolio ficou abaixo do seu pico. Periodos de drawdown prolongado sao os mais dificeis de aguentar na pratica.")

    h2(doc, "Bloco 7 — Salvar Parquets")
    cod(doc, "pesos_v1.to_parquet('../../dados/pesos_v1.parquet')")
    cod(doc, "ret_v1.to_frame('retorno').to_parquet('../../dados/retorno_carteira_v1.parquet')")
    cod(doc, "print('Parquets da Aula 5 salvos.')")

    div(doc)
    h1(doc, "FECHAMENTO DA AULA 5")
    tempo(doc, "1:55 – 2:00")
    div(doc)
    fala(doc, "Excelente — primeiro backtest completo. Vocês ja tem uma estrategia quantitativa funcionando com metricas calculadas. Mas lembrem: sem custos, sem rigor total. Nas proximas aulas vamos melhorar o sinal e a alocacao, e na Aula 8 vamos adicionar rigor completo.")

    pasta = os.path.join(BASE, "aula-05-backtest-v1")
    doc.save(os.path.join(pasta, "roteiro-aula-05-backtest-v1.docx"))
    print("  Aula 05: roteiro salvo -> aula-05-backtest-v1/")


# ══════════════════════════════════════════════════════════════
# AULA 06 — ALOCACAO
# ══════════════════════════════════════════════════════════════
def aula06():
    doc = novo_doc("06", "Alocacao: Como Pesar as Acoes do Portfolio")

    h1(doc, "ABERTURA")
    tempo(doc, "0:00 – 0:03")
    div(doc)
    fala(doc, "Bem-vindos a Aula 6. Na Aula 5 usamos equal-weight — 10% para cada acao. Isso e simples e robusto, mas sera que da para fazer melhor? Hoje vamos explorar a Teoria Moderna de Portfolio de Markowitz de duas formas: a otimizacao pura (sem restricoes de ativos) e a otimizacao restrita (com limites reais de 0% a 20%), e compara-las com a nossa baseline no mesmo sinal.")
    fala(doc, "Uma coisa importante: vamos manter o sinal v1 fixo. A unica variavel e o esquema de pesos. Assim podemos atribuir qualquer diferenca de performance a escolha de alocacao — nao ao sinal.")

    div(doc)
    h1(doc, "PARTE 1 — TEORIA (20 min)")
    tempo(doc, "0:03 – 0:20")
    div(doc)

    acao(doc, "Avancar slide 3: Esquemas de Alocacao")
    h2(doc, "Por que a Alocacao Importa")
    fala(doc, "Existe um dito no mercado: 'a alocacao e responsavel por mais de 90% da variacao de retorno de longo prazo'. A selecao de acoes e o market timing contribuem pouco em comparacao com a decisao de quanto alocar em cada categoria.")
    fala(doc, "No nosso contexto, a alocacao tem dois papeis. Primeiro, determina o quanto cada acao contribui para o risco do portfolio. Segundo, determina o turnover: quanto o portfolio precisa ser rebalanceado a cada mes, o que gera custos de transacao.")
    fala(doc, "Os tres esquemas que vamos comparar hoje sao: Equal-Weight (nossa baseline de 1/N), Markowitz Puro (otimizacao sem restricoes adicionais) e Markowitz Restrito (otimizacao com pesos limitados entre 0% e 20% e que somam 1).")

    h2(doc, "Equal-Weight — O Poder da Simplicidade")
    fala(doc, "Equal-weight e o esquema mais simples possivel: todas as acoes selecionadas recebem o mesmo peso. No nosso caso, 10% para cada uma das top 10.")
    fala(doc, "Por que isso funciona tao bem? DeMiguel, Garlappi e Uppal em 2009 deram a resposta: a otimizacao de Markowitz requer estimacoes precisas de retornos esperados e da matriz de covariancia. Essas estimacoes tem erro amostral significativo — especialmente com janelas curtas. O equal-weight evita esse problema completamente.")

    h2(doc, "Markowitz Puro (Mean-Variance) — A Teoria Classica")
    fala(doc, "A Teoria Moderna de Portfolio de Markowitz de 1952 otimiza os pesos para maximizar o Sharpe Ratio: maximizar o retorno esperado do portfolio dividido pelo seu desvio padrao (volatilidade), sujeito a pesos positivos que somam 1.")
    fala(doc, "A formula de otimizacao resolve:")
    fala(doc, "Maximizar Sharpe = (w.T @ mu - rf) / sqrt(w.T @ Sigma @ w)")
    fala(doc, "Sujeito a: sum(w) = 1 e w >= 0 (long-only).")
    fala(doc, "O problema pratico: sem restricoes adicionais, a otimizacao e extremamente sensivel. Ela tende a concentrar drasticamente o portfolio em 1 ou 2 acoes que pareceram otimas no in-sample, gerando riscos enormes e alta instabilidade (alto turnover).")

    h2(doc, "Markowitz Restrito — A Ponte Pratica")
    fala(doc, "Para resolver o problema da instabilidade, a industria quantitativa aplica restricoes adicionais. Vamos limitar o peso maximo de qualquer ativo a 20% (bounds de 0% a 20%), garantindo diversificacao minima mesmo que a otimizacao tente concentrar.")
    fala(doc, "Isso reduz a sensibilidade a erros de estimativa e produz portfolios robustos fora da amostra, com turnover muito mais controlado.")

    div(doc)
    h1(doc, "PARTE 2 — LIVE CODING (40 min)")
    tempo(doc, "0:20 – 0:55")
    div(doc)

    acao(doc, "Abrir notebook: aulas/aula-06-alocacao/aula-06-alocacao.ipynb")

    h2(doc, "Bloco 1 — Carregar Dados")
    cod(doc, "import pandas as pd, numpy as np")
    cod(doc, "import matplotlib.pyplot as plt")
    cod(doc, "from scipy import optimize")
    cod(doc, "")
    cod(doc, "ret_diarios = pd.read_parquet('../../dados/retornos_diarios_limpo.parquet')")
    cod(doc, "ret_mensais = pd.read_parquet('../../dados/retornos_mensais_limpo.parquet')")
    cod(doc, "sinal_v1    = pd.read_parquet('../../dados/sinal_v1.parquet')")

    h2(doc, "Bloco 2 — Otimizacao de Markowitz Pura")
    cod(doc, "def pesos_markowitz_puro(sinal, ret_mensais, n_top=10, janela_hist=36):")
    cod(doc, "    pesos = pd.DataFrame(0.0, index=sinal.index, columns=sinal.columns)")
    cod(doc, "    for i, data in enumerate(sinal.index):")
    cod(doc, "        if i < janela_hist: continue")
    cod(doc, "        s = sinal.loc[data].dropna()")
    cod(doc, "        if len(s) < n_top: continue")
    cod(doc, "        top = s.nlargest(n_top).index")
    cod(doc, "        hist = ret_mensais.loc[:data].tail(janela_hist)[top].dropna(axis=1)")
    cod(doc, "        if hist.shape[1] < 3: continue")
    cod(doc, "        mu  = hist.mean().values")
    cod(doc, "        cov = hist.cov().values")
    cod(doc, "        n   = len(mu)")
    cod(doc, "        def neg_sharpe(w):")
    cod(doc, "            ret = w @ mu")
    cod(doc, "            vol = np.sqrt(w @ cov @ w)")
    cod(doc, "            return -ret / vol if vol > 1e-8 else 0")
    cod(doc, "        constraints = [{'type': 'eq', 'fun': lambda w: w.sum() - 1}]")
    cod(doc, "        bounds = [(0.0, 1.0)] * n")
    cod(doc, "        w0 = np.ones(n) / n")
    cod(doc, "        res = optimize.minimize(neg_sharpe, w0, method='SLSQP', bounds=bounds, constraints=constraints)")
    cod(doc, "        if res.success:")
    cod(doc, "            pesos.loc[data, hist.columns] = res.x")
    cod(doc, "    return pesos")

    h2(doc, "Bloco 3 — Otimizacao de Markowitz Restrita (Bounds de 0% a 20%)")
    cod(doc, "def pesos_markowitz_restrito(sinal, ret_mensais, n_top=10, janela_hist=36):")
    cod(doc, "    pesos = pd.DataFrame(0.0, index=sinal.index, columns=sinal.columns)")
    cod(doc, "    for i, data in enumerate(sinal.index):")
    cod(doc, "        if i < janela_hist: continue")
    cod(doc, "        s = sinal.loc[data].dropna()")
    cod(doc, "        if len(s) < n_top: continue")
    cod(doc, "        top = s.nlargest(n_top).index")
    cod(doc, "        hist = ret_mensais.loc[:data].tail(janela_hist)[top].dropna(axis=1)")
    cod(doc, "        if hist.shape[1] < 3: continue")
    cod(doc, "        mu  = hist.mean().values")
    cod(doc, "        cov = hist.cov().values")
    cod(doc, "        n   = len(mu)")
    cod(doc, "        def neg_sharpe(w):")
    cod(doc, "            ret = w @ mu")
    cod(doc, "            vol = np.sqrt(w @ cov @ w)")
    cod(doc, "            return -ret / vol if vol > 1e-8 else 0")
    cod(doc, "        constraints = [{'type': 'eq', 'fun': lambda w: w.sum() - 1}]")
    cod(doc, "        # Restricao crucial: peso maximo de 20% por ativo (0 a 0.2)")
    cod(doc, "        bounds = [(0.0, 0.20)] * n")
    cod(doc, "        w0 = np.ones(n) / n")
    cod(doc, "        res = optimize.minimize(neg_sharpe, w0, method='SLSQP', bounds=bounds, constraints=constraints)")
    cod(doc, "        if res.success:")
    cod(doc, "            pesos.loc[data, hist.columns] = res.x")
    cod(doc, "    return pesos")

    h2(doc, "Bloco 4 — Comparar os Esquemas de Alocacao")
    cod(doc, "def retorno_carteira(pesos_df, ret_mensais):")
    cod(doc, "    ret_c = (pesos_df.shift(1) * ret_mensais).sum(axis=1)")
    cod(doc, "    return ret_c[ret_c != 0]")
    cod(doc, "")
    cod(doc, "# Calcular pesos de cada carteira")
    cod(doc, "pw_ew, ret_ew = construir_portfolio(sinal_v1, ret_mensais, 10)  # da Aula 5")
    cod(doc, "pw_puro = pesos_markowitz_puro(sinal_v1, ret_mensais, 10)")
    cod(doc, "ret_puro = retorno_carteira(pw_puro, ret_mensais)")
    cod(doc, "")
    cod(doc, "pw_restrito = pesos_markowitz_restrito(sinal_v1, ret_mensais, 10)")
    cod(doc, "ret_restrito = retorno_carteira(pw_restrito, ret_mensais)")

    h2(doc, "Bloco 5 — Analise de Turnover e Métricas")
    cod(doc, "def calcular_turnover(pesos_df):")
    cod(doc, "    delta = pesos_df.diff().abs().sum(axis=1) / 2")
    cod(doc, "    return delta[delta > 0]")
    cod(doc, "")
    cod(doc, "print('Turnover Mensal Medio:')")
    cod(doc, "print(f'  Equal-Weight:       {calcular_turnover(pw_ew).mean():.1%}')")
    cod(doc, "print(f'  Markowitz Puro:     {calcular_turnover(pw_puro).mean():.1%}')")
    cod(doc, "print(f'  Markowitz Restrito: {calcular_turnover(pw_restrito).mean():.1%}')")
    fala(doc, "Voces vao notar o absurdo: o Markowitz Puro rebalanceia quase todo o portfolio a cada mes (turnover altissimo), enquanto a versao Restrita mantem pesos mais estaveis, reduzindo drasticamente os custos.")

    h2(doc, "Bloco 6 — Salvar Parquets")
    cod(doc, "pw_restrito.to_parquet('../../dados/pesos_v2.parquet')")
    cod(doc, "ret_restrito.to_frame('retorno').to_parquet('../../dados/retorno_carteira_v2.parquet')")
    cod(doc, "print('Esquema Markowitz Restrito escolhido e salvo como pesos_v2.parquet.')")

    div(doc)
    h1(doc, "FECHAMENTO DA AULA 6")
    tempo(doc, "0:55 – 1:00")
    div(doc)
    fala(doc, "Hoje comparamos a Teoria Classica de Markowitz em sua forma Pura versus a Pratica Restrita (Long-Only + Bounds de 20%). A conclusao e muito clara: complexidade teorica sem restricoes reais gera overfitting, alta concentracao e turnover insustentavel. A otimizacao restrita e o melhor dos dois mundos. Na proxima aula, vamos sofisticar o sinal incorporando ajuste por volatilidade.")

    pasta = os.path.join(BASE, "aula-06-alocacao")
    os.makedirs(pasta, exist_ok=True)
    doc.save(os.path.join(pasta, "roteiro-aula-06-alocacao.docx"))
    print("  Aula 06: roteiro salvo -> aula-06-alocacao/")

def aula07():
    doc = novo_doc("07", "Sinal v2: Momentum Ajustado por Volatilidade")

    h1(doc, "ABERTURA")
    tempo(doc, "0:00 – 0:05")
    div(doc)
    fala(doc, "Bem-vindos a Aula 7. Hoje vamos melhorar o sinal. O sinal v1 usa retorno bruto acumulado — mas retorno bruto ignora risco. Uma acao que subiu 40% com volatilidade anual de 70% e fundamentalmente diferente de uma que subiu 30% com volatilidade de 20%. O sinal v2 corrige isso dividindo o retorno pela volatilidade historica.")

    div(doc)
    h1(doc, "PARTE 1 — TEORIA (20 min)")
    tempo(doc, "0:05 – 0:25")
    div(doc)

    acao(doc, "Avancar slide 3: Limitacao do Sinal v1")
    h2(doc, "Por que Retorno Bruto e Incompleto")
    fala(doc, "O sinal v1 seleciona as acoes com maior retorno acumulado. Mas pensa no seguinte: se uma acao subiu 40% e outra subiu 30%, qual a gente prefere para o portfolio?")
    fala(doc, "A resposta nao e necessariamente a que subiu mais. Se a acao de 40% tem o dobro de volatilidade, ela pode estar assumindo o dobro de risco para gerar um retorno apenas 33% maior. Em termos ajustados por risco — uma especie de Sharpe-like do periodo de formacao — a acao de 30% pode ser preferivel.")
    fala(doc, "O sinal v2 faz exatamente isso: divide o retorno acumulado pela volatilidade historica. Se acao A tem retorno 12-1 de 0.40 e vol anual de 0.60, o sinal v2 e 0.40/0.60 = 0.67. Se acao B tem retorno de 0.30 e vol de 0.20, o sinal v2 e 0.30/0.20 = 1.50. O ranking v2 prefere B — e provavelmente esta certo.")
    fala(doc, "Isso tem um embasamento academico solido. Moskowitz, Ooi e Pedersen em 2012 — no paper sobre time-series momentum — mostraram que dividir o sinal pela volatilidade historica melhora a performance e reduz o risco do portfolio. A intuicao e que normalizar pelo risco torna o sinal mais comparavel entre ativos com perfis de risco diferentes.")

    acao(doc, "Avancar slide 4: Comparacao v1 vs v2")
    h2(doc, "Como Comparar Dois Sinais de Forma Justa")
    fala(doc, "Para comparar v1 e v2 honestamente, precisamos manter tudo igual exceto o sinal: mesmo universo, mesmo n de acoes, mesmo esquema de pesos, mesmo periodo, mesmas metricas. So o sinal muda.")
    fala(doc, "O que esperar: o IC do v2 deve ser ligeiramente maior. O Sharpe do portfolio com v2 deve ser ligeiramente melhor. A melhora nao vai ser dramatica — afinal, o sinal v1 ja e bom. Mas a direcao deve ser consistente. Se v2 for pior em tudo, ha algo errado na implementacao.")

    div(doc)
    h1(doc, "PARTE 2 — LIVE CODING (95 min)")
    tempo(doc, "0:25 – 2:00")
    div(doc)

    acao(doc, "Abrir notebook: aulas/aula-07-sinal-v2/aula-07-sinal-v2.ipynb")

    h2(doc, "Bloco 1 — Calcular Volatilidade Rolling")
    cod(doc, "import pandas as pd, numpy as np")
    cod(doc, "import matplotlib.pyplot as plt")
    cod(doc, "from scipy import stats")
    cod(doc, "")
    cod(doc, "ret_diarios = pd.read_parquet('../../dados/retornos_diarios_limpo.parquet')")
    cod(doc, "ret_mensais = pd.read_parquet('../../dados/retornos_mensais_limpo.parquet')")
    cod(doc, "sinal_v1    = pd.read_parquet('../../dados/sinal_v1.parquet')")
    cod(doc, "")
    cod(doc, "# Volatilidade anualizada rolling de 63 dias uteis")
    cod(doc, "JANELA_VOL = 63")
    cod(doc, "vol_rolling = ret_diarios.rolling(JANELA_VOL).std() * np.sqrt(252)")
    cod(doc, "")
    cod(doc, "# Resamplar para frequencia mensal — ultimo dia do mes")
    cod(doc, "vol_mensal = vol_rolling.resample('ME').last()")
    cod(doc, "")
    cod(doc, "print('Vol rolling shape:', vol_rolling.shape)")
    cod(doc, "print('Vol mensal shape:', vol_mensal.shape)")
    cod(doc, "print(f'Volatilidade media: {vol_mensal.stack().mean():.1%}')")
    fala(doc, "Por que 63 dias uteis? E aproximadamente 3 meses de negociacao. E uma janela padrao na literatura — curta o suficiente para ser reativa a mudancas de regime, longa o suficiente para ser estatisticamente estavel.")
    fala(doc, "Por que usar a frequencia diaria para calcular vol e depois resampling? Porque com dados diarios temos mais pontos — 63 observacoes em vez de 3 mensais — o que torna a estimativa muito mais precisa. A frequencia mensal simplesmente nao tem observacoes suficientes para estimar volatilidade com confianca.")

    h2(doc, "Bloco 2 — Construir Sinal v2")
    cod(doc, "# Sinal v2: sinal_v1 / volatilidade")
    cod(doc, "# Alinhar indices antes de dividir")
    cod(doc, "vol_alinhada = vol_mensal.reindex(sinal_v1.index)")
    cod(doc, "")
    cod(doc, "# Divisao elemento a elemento — automatica pelo pandas")
    cod(doc, "sinal_v2 = sinal_v1 / vol_alinhada")
    cod(doc, "")
    cod(doc, "# Substituir valores infinitos (vol=0) por NaN")
    cod(doc, "sinal_v2 = sinal_v2.replace([np.inf, -np.inf], np.nan)")
    cod(doc, "")
    cod(doc, "print(f'Sinal v1 — media: {sinal_v1.stack().mean():.4f}')")
    cod(doc, "print(f'Sinal v2 — media: {sinal_v2.stack().mean():.4f}')")
    cod(doc, "print(f'Correlacao v1 vs v2: {sinal_v1.corrwith(sinal_v2, axis=1).mean():.3f}')")
    fala(doc, "A correlacao entre v1 e v2 deve ser alta — em torno de 0.7 a 0.85. Os sinais concordam na maioria dos casos, mas diferem em situacoes onde acoes com alto retorno bruto tem volatilidade muito alta. Sao exatamente esses casos que o v2 corrige.")

    h2(doc, "Bloco 3 — Comparar IC v1 vs v2")
    cod(doc, "from scipy.stats import spearmanr")
    cod(doc, "")
    cod(doc, "def calcular_ic_serie(sinal, retornos):")
    cod(doc, "    ret_futuro = retornos.shift(-1)")
    cod(doc, "    ic_list = []")
    cod(doc, "    for data in sinal.dropna(how='all').index:")
    cod(doc, "        s = sinal.loc[data].dropna()")
    cod(doc, "        r = ret_futuro.loc[data].reindex(s.index).dropna()")
    cod(doc, "        s = s.reindex(r.index)")
    cod(doc, "        if len(r) >= 10:")
    cod(doc, "            ic, _ = spearmanr(s, r)")
    cod(doc, "            ic_list.append({'data': data, 'ic': ic})")
    cod(doc, "    return pd.DataFrame(ic_list).set_index('data')['ic']")
    cod(doc, "")
    cod(doc, "ic_v1 = calcular_ic_serie(sinal_v1, ret_mensais)")
    cod(doc, "ic_v2 = calcular_ic_serie(sinal_v2, ret_mensais)")
    cod(doc, "")
    cod(doc, "print('=== COMPARACAO DE IC ===')")
    cod(doc, "for nome, ic in [('v1', ic_v1), ('v2', ic_v2)]:")
    cod(doc, "    tstat = ic.mean() / (ic.std() / np.sqrt(len(ic)))")
    cod(doc, "    print(f'Sinal {nome}: IC={ic.mean():.4f}, t-stat={tstat:.2f}, hit={( ic>0).mean():.1%}')")

    h2(doc, "Bloco 4 — Backtest Comparativo")
    cod(doc, "# Portfolio com sinal v1 (equal-weight)")
    cod(doc, "def construir_portfolio(sinal, ret_mensais, n_top=10):")
    cod(doc, "    pesos = pd.DataFrame(0.0, index=sinal.index, columns=sinal.columns)")
    cod(doc, "    for data in sinal.index:")
    cod(doc, "        s = sinal.loc[data].dropna()")
    cod(doc, "        if len(s) >= n_top:")
    cod(doc, "            pesos.loc[data, s.nlargest(n_top).index] = 1.0 / n_top")
    cod(doc, "    ret = (pesos.shift(1) * ret_mensais).sum(axis=1)")
    cod(doc, "    return pesos, ret[ret != 0]")
    cod(doc, "")
    cod(doc, "pesos_v1, ret_carteira_v1 = construir_portfolio(sinal_v1, ret_mensais)")
    cod(doc, "pesos_v2, ret_carteira_v2 = construir_portfolio(sinal_v2, ret_mensais)")
    cod(doc, "ret_ibov = ret_mensais.mean(axis=1)")
    cod(doc, "")
    cod(doc, "# Calcular metricas para ambos")
    cod(doc, "# (usar funcao calcular_metricas da Aula 5)")
    cod(doc, "m_v1 = calcular_metricas(ret_carteira_v1, ret_ibov, 'Sinal v1')")
    cod(doc, "m_v2 = calcular_metricas(ret_carteira_v2, ret_ibov, 'Sinal v2')")
    cod(doc, "m_ibov = calcular_metricas(ret_ibov, nome='IBOV')")
    cod(doc, "exibir_metricas(m_v1, m_v2, m_ibov)")

    h2(doc, "Bloco 5 — Grafico Comparativo")
    cod(doc, "fig, axes = plt.subplots(2, 1, figsize=(14, 10))")
    cod(doc, "periodo = ret_carteira_v1.index.intersection(ret_carteira_v2.index)")
    cod(doc, "")
    cod(doc, "ax = axes[0]")
    cod(doc, "for ret, label, cor in [(ret_carteira_v1, 'Sinal v1', 'steelblue'),")
    cod(doc, "                         (ret_carteira_v2, 'Sinal v2', 'navy'),")
    cod(doc, "                         (ret_ibov.reindex(periodo), 'IBOV', 'gray')]:")
    cod(doc, "    cum = (1 + ret.reindex(periodo)).cumprod()")
    cod(doc, "    ax.plot(cum, label=label, lw=2 if label != 'IBOV' else 1, color=cor,")
    cod(doc, "            ls='-' if label != 'IBOV' else '--')")
    cod(doc, "ax.set_title('Retorno Acumulado: Sinal v1 vs Sinal v2')")
    cod(doc, "ax.legend(); ax.grid(alpha=0.3)")
    cod(doc, "")
    cod(doc, "ax2 = axes[1]")
    cod(doc, "ic_comp = pd.DataFrame({'v1': ic_v1, 'v2': ic_v2}).rolling(12).mean()")
    cod(doc, "ax2.plot(ic_comp['v1'], label='IC v1 (12m)', color='steelblue')")
    cod(doc, "ax2.plot(ic_comp['v2'], label='IC v2 (12m)', color='navy', ls='--')")
    cod(doc, "ax2.axhline(0, color='gray', lw=0.5)")
    cod(doc, "ax2.set_title('IC Movel 12 meses: v1 vs v2')")
    cod(doc, "ax2.legend(); plt.tight_layout()")
    cod(doc, "plt.savefig('comparacao_v1_v2.png', dpi=150); plt.show()")

    h2(doc, "Bloco 6 — Salvar Parquets v2")
    cod(doc, "sinal_v2.to_parquet('../../dados/sinal_v2.parquet')")
    cod(doc, "pesos_v2.to_parquet('../../dados/pesos_sinal_v2.parquet')")
    cod(doc, "ret_carteira_v2.to_frame('retorno').to_parquet('../../dados/retorno_carteira_sinal_v2.parquet')")
    cod(doc, "print('Parquets v2 salvos.')")

    div(doc)
    h1(doc, "FECHAMENTO DA AULA 7")
    tempo(doc, "1:55 – 2:00")
    div(doc)
    fala(doc, "Temos agora dois sinais: v1 com retorno bruto e v2 com retorno vol-ajustado. Na Aula 8, vamos adicionar rigor completo ao backtest: look-ahead bias, overfitting, custos e walk-forward. Essa e a aula mais critica do intensivao — nao percam.")

    pasta = os.path.join(BASE, "aula-07-sinal-v2")
    doc.save(os.path.join(pasta, "roteiro-aula-07-sinal-v2.docx"))
    print("  Aula 07: roteiro salvo -> aula-07-sinal-v2/")


if __name__ == "__main__":
    print("Gerando roteiros das aulas 04, 05, 06, 07...")
    aula04()
    aula05()
    aula06()
    aula07()
    print("Concluido!")
