"""
Roteiros Aulas 1, 2, 3 — Intensivao Quant AI
python gerar_roteiros_parte1.py
"""
import os
from docx import Document
from docx.shared import Pt, RGBColor, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH

BASE = os.path.dirname(os.path.abspath(__file__))


def novo_doc(num, titulo):
    doc = Document()
    for s in doc.sections:
        s.top_margin = Cm(2.5)
        s.bottom_margin = Cm(2.5)
        s.left_margin = Cm(3.0)
        s.right_margin = Cm(2.5)
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run(f"INTENSIVAO QUANT AI — AULA {num}")
    r.font.size = Pt(11); r.font.bold = True
    r.font.color.rgb = RGBColor(0xF5, 0xA6, 0x23)
    p2 = doc.add_paragraph()
    p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r2 = p2.add_run(titulo)
    r2.font.size = Pt(20); r2.font.bold = True
    r2.font.color.rgb = RGBColor(0x0D, 0x1B, 0x3E)
    p3 = doc.add_paragraph()
    p3.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r3 = p3.add_run("Roteiro completo — uso exclusivo do instrutor")
    r3.font.size = Pt(10); r3.font.italic = True
    r3.font.color.rgb = RGBColor(0x88, 0x88, 0x88)
    doc.add_paragraph()
    return doc


def h1(doc, t):
    p = doc.add_heading(level=1); p.clear()
    r = p.add_run(t); r.font.size = Pt(15); r.font.bold = True
    r.font.color.rgb = RGBColor(0x0D, 0x1B, 0x3E)

def h2(doc, t):
    p = doc.add_heading(level=2); p.clear()
    r = p.add_run(t); r.font.size = Pt(13); r.font.bold = True
    r.font.color.rgb = RGBColor(0x1A, 0x6E, 0xAE)

def h3(doc, t):
    p = doc.add_heading(level=3); p.clear()
    r = p.add_run(t); r.font.size = Pt(11); r.font.bold = True
    r.font.color.rgb = RGBColor(0x1E, 0x8B, 0x4C)

def fala(doc, t):
    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(8)
    r = p.add_run(t); r.font.size = Pt(11)
    r.font.color.rgb = RGBColor(0x1A, 0x1A, 0x1A)

def acao(doc, t):
    p = doc.add_paragraph()
    r = p.add_run(f"[{t}]")
    r.font.size = Pt(10); r.font.italic = True
    r.font.color.rgb = RGBColor(0x88, 0x44, 0x00)

def cod(doc, t):
    p = doc.add_paragraph()
    p.paragraph_format.left_indent = Inches(0.4)
    r = p.add_run(t)
    r.font.name = 'Courier New'; r.font.size = Pt(10)
    r.font.color.rgb = RGBColor(0x1A, 0x6E, 0xAE)

def tempo(doc, t):
    p = doc.add_paragraph()
    r = p.add_run(f"  {t}")
    r.font.size = Pt(9); r.font.bold = True
    r.font.color.rgb = RGBColor(0xF5, 0xA6, 0x23)

def div(doc):
    p = doc.add_paragraph()
    r = p.add_run("─" * 70)
    r.font.size = Pt(8); r.font.color.rgb = RGBColor(0xCC, 0xCC, 0xCC)


# ══════════════════════════════════════════════════════════════
# AULA 01 — KICKOFF
# ══════════════════════════════════════════════════════════════
def aula01():
    doc = novo_doc("01", "Kickoff: Fundamentos do Mercado Financeiro")

    h1(doc, "ABERTURA")
    tempo(doc, "0:00 – 0:05  |  Apresentacao e contexto")
    div(doc)

    fala(doc, "Pessoal, boa tarde e bem-vindos ao Intensivao Quant AI da ImpactUFSCar. Quem ainda nao me conhece, meu nome e Felipe Maldonado, sou VP e lider tecnico da Diretoria Quant.")
    fala(doc, "Nas proximas cinco semanas — dez aulas ao todo — vamos construir juntos uma estrategia quantitativa completa. Do zero absoluto ao relatorio final, pronto para ser apresentado ao juri do Desafio Quant AI da Itau Asset Management.")
    fala(doc, "O formato vai ser sempre o mesmo em cada aula: primeiro a gente passa por teoria — de 20 a 30 minutos — para entender o porque de cada decisao que vamos tomar. Depois e live coding: eu digito na frente de voces, voces replicam no computador de voces. Ao final de cada aula, voces tem um notebook funcionando que avanca a estrategia um passo.")
    fala(doc, "Hoje e a aula de kickoff. A mais teorica de todas. Nao vamos escrever muito codigo hoje — mas o que a gente discutir aqui e a fundacao conceitual de tudo que vem depois. Se voces entenderem bem o que e momentum, por que ele existe e por que persiste, voces vao conseguir defender cada decisao da estrategia quando o juri perguntar.")

    acao(doc, "Verificar com a turma: todos tem Python e Jupyter instalados? Quem ainda nao tem, orientar para instalar durante a semana")
    fala(doc, "Antes de comecar, uma pergunta rapida: alguem aqui ja investiu em bolsa? Ja ouviu falar em fundo quant? Perfeito — o nivel de familiaridade varia e tudo bem, a gente vai construir do basico.")

    div(doc)
    h1(doc, "PARTE 1 — O ECOSSISTEMA FINANCEIRO")
    tempo(doc, "0:05 – 0:20  |  Classes de ativos e seus papeis")
    div(doc)

    acao(doc, "Avancar para o slide 3: O Ecossistema Financeiro Global")
    fala(doc, "Vamos comecar do comeco. O que e o mercado financeiro e por que ele existe?")
    fala(doc, "Pensa assim: de um lado voce tem quem poupa — pessoas fisicas, fundos de pensao, seguradoras. Do outro lado voce tem quem precisa de capital para investir — empresas querendo construir fabrica, governo querendo construir estrada, startups querendo crescer. O mercado financeiro e o mecanismo que conecta esses dois lados. E cada classe de ativo representa um contrato diferente entre quem poupa e quem precisa do capital.")
    fala(doc, "Olhando para o grafico que esta no slide: o mercado global de renda fixa tem cerca de 130 trilhoes de dolares. Renda variavel, uns 110 trilhoes em market cap. E derivativos, em termos de valor nocional, ultrapassa 600 trilhoes. Esses numeros sao de 2024, do BIS — Banco de Compensacoes Internacionais.")
    fala(doc, "Por que isso importa para nos? Porque cada classe de ativo tem um perfil de risco e retorno muito diferente. E quando a gente constroi uma estrategia quant, a gente precisa entender em qual oceano a gente esta nadando.")

    acao(doc, "Avancar para o slide 4: Renda Fixa")
    h2(doc, "Renda Fixa")
    fala(doc, "Renda fixa. Quando voce compra um titulo de renda fixa, voce esta essencialmente emprestando dinheiro para alguem — o governo federal, um banco, uma empresa. Em troca, eles prometem pagar de volta o principal mais uma remuneracao que chamamos de cupom.")
    fala(doc, "O nome 'renda fixa' pode ser um pouco enganoso. O retorno e fixo em termos de estrutura contratual — mas o preco de mercado do titulo flutua diariamente. Se a taxa de juros sobe, o preco dos titulos cai. E vice-versa. Isso e o que chamamos de risco de duration.")
    fala(doc, "No Brasil, a gente tem tres grandes categorias de renda fixa publica. O Tesouro Selic — ou LFT — que rende a taxa Selic diariamente, risco minimo. O Tesouro Prefixado — LTN — com taxa travada no momento da compra, mas sujeito a volatilidade de preco se voce vender antes do vencimento. E o Tesouro IPCA+ — NTN-B — que paga IPCA mais um spread, protegendo contra inflacao.")
    fala(doc, "Tem uma metrica que e fundamental em renda fixa que se chama duration — desenvolvida por Frederick Macaulay em 1938. Ela mede a sensibilidade do preco do titulo a variacoes na taxa de juros. Quanto maior a duration, mais o titulo oscila quando os juros mexem. Uma NTN-B com vencimento em 2050 tem duration altissima — sobe e cai muito com o mercado. Um CDB de 30 dias tem duration de 30 dias — quase nao oscila.")
    fala(doc, "Por que isso e relevante para nos? Porque quando construimos nossa estrategia de acoes, o benchmark de comparacao e sempre o CDI — a taxa basica do mercado de credito. E precisamos gerar retorno acima do CDI para justificar o risco de estar em renda variavel.")

    acao(doc, "Avancar para o slide 5: Renda Variavel")
    h2(doc, "Renda Variavel")
    fala(doc, "Renda variavel. Quando voce compra uma acao, voce esta comprando uma fracao da propriedade de uma empresa. Voce tem direito aos lucros futuros — na forma de dividendos ou valorizacao do preco — mas arca com toda a variabilidade dos resultados.")
    fala(doc, "A pergunta que voce deveria se fazer e: por que alguem em sã consciencia compraria algo tao imprevisivel? A resposta e o equity risk premium — o premio de risco de acoes.")
    fala(doc, "Mehra e Prescott em 1985 documentaram um puzzle que ficou famoso: historicamente, acoes nos EUA renderam cerca de 5 a 6 pontos percentuais a mais por ano do que titulos soberanos, em termos reais. Eles chamaram isso de puzzle porque modelos economicos nao conseguiam explicar um premio tao alto. A conclusao pratica: acoes remuneram melhor no longo prazo, mas voce precisa aguentar a volatilidade no caminho.")
    fala(doc, "No Brasil, o equity risk premium historico e em torno de 6% ao ano sobre o CDI. Parece pouco? Em 30 anos, a diferenca entre um investimento que rende CDI e outro que rende CDI+6% e abissal. Um real investido em 1994 viraria uns R$30 em renda fixa e mais de R$300 em renda variavel — se voce conseguisse replicar o indice sem custos. Na pratica e mais complexo, mas a direcao e essa.")
    fala(doc, "Os veiculos de investimento em renda variavel no Brasil sao principalmente: acoes individuais na B3, ETFs como o BOVA11 que replica o IBOVESPA ou o IVVB11 que replica o S&P 500, e BDRs — Brazilian Depositary Receipts — que sao certificados de acoes estrangeiras negociados na B3.")

    acao(doc, "Avancar para o slide 6: Derivativos e Alternativos")
    h2(doc, "Derivativos e Ativos Alternativos")
    fala(doc, "Rapidamente sobre derivativos: sao contratos que derivam seu valor de um ativo-objeto. Os tres mais importantes para nos conhecermos sao futuros, opcoes e swaps.")
    fala(doc, "Futuros: obrigacao de comprar ou vender algo a um preco fixado hoje, em data futura. Uma exportadora de soja que vai receber dolares em 3 meses usa futuros de dolar para travar o cambio hoje — isso e hedge.")
    fala(doc, "Opcoes: direito — nao obrigacao — de comprar ou vender a um preco determinado. O modelo de Black e Scholes de 1973 formalizou o apreçamento dessas opcoes e foi um divisor de aguas nas financas quantitativas. Fisher Black e Myron Scholes ganharam o Nobel por isso.")
    fala(doc, "E os alternativos — FIIs, private equity, venture capital, commodities, ouro. Esses ativos tem baixa correlacao com o mercado de acoes em condicoes normais, o que os torna interessantes para diversificacao. Vamos falar pouco sobre eles neste intensivao porque nossa estrategia e focada em acoes — mas voces devem saber que existem e qual o papel deles.")

    div(doc)
    h1(doc, "PARTE 2 — TEORIA DE PORTFOLIO E MERCADOS EFICIENTES")
    tempo(doc, "0:20 – 0:35  |  MPT, CAPM e HME")
    div(doc)

    acao(doc, "Avancar para o slide 7: Teoria Moderna de Portfolio")
    h2(doc, "Teoria Moderna de Portfolio (MPT)")
    fala(doc, "Em 1952, um economista chamado Harry Markowitz publicou um artigo no Journal of Finance que mudou para sempre a gestao de investimentos. O titulo era simples: 'Portfolio Selection'. E o insight central era elegante: o que importa nao e o risco de cada ativo isoladamente, mas a contribuicao de cada ativo ao risco total do portfolio — que depende das correlacoes.")
    fala(doc, "Antes de Markowitz, a sabedoria popular dizia 'nao coloque todos os ovos na mesma cesta'. Markowitz matematizou isso. Ele mostrou que ao combinar ativos com correlacao menor que 1, voce reduz o risco do portfolio sem necessariamente reduzir o retorno esperado. Isso e o que chamamos de diversificacao.")
    fala(doc, "A extensao mais famosa do trabalho de Markowitz e o CAPM — Capital Asset Pricing Model — desenvolvido por William Sharpe em 1964. O CAPM diz que em equilibrio, o retorno esperado de um ativo e proporcional ao seu beta — a sua correlacao com o mercado. O beta mede o risco sistematico, que nao pode ser eliminado por diversificacao.")
    fala(doc, "Mas tem um resultado pratico muito importante de estudos mais recentes que voces precisam saber: DeMiguel, Garlappi e Uppal em 2009 testaram 14 modelos de portfolio otimizado contra o portfolio igual em 14 datasets diferentes. Em 11 dos 14, o portfolio 1/N — igual para todos — ganhou do portfolio otimizado fora da amostra. Por que? Porque a otimizacao amplifica os erros de estimacao dos parametros. E isso tem uma implicacao direta para nossa estrategia: vamos usar equal-weight como nossa baseline, e qualquer esquema mais complexo tem que provar que vale a pena.")

    acao(doc, "Avancar para o slide 8: Hipotese dos Mercados Eficientes")
    h2(doc, "A Hipotese dos Mercados Eficientes")
    fala(doc, "Agora chegamos na teoria mais importante e mais controversa das financas: a Hipotese dos Mercados Eficientes, ou HME. Formulada por Eugene Fama em 1970 — que ganhou o Nobel em 2013.")
    fala(doc, "A hipotese diz: em um mercado eficiente, os precos refletem instantaneamente toda a informacao relevante disponivel. A implicacao: nenhum agente consegue consistentemente obter retorno acima do risco que assume.")
    fala(doc, "Fama definiu tres formas de eficiencia. A forma fraca: precos incorporam todo o historico de precos e volumes. Implicacao: analise tecnica — os graficos — nao funcionam. A forma semi-forte: precos refletem toda informacao publica — balancetes, noticias, dados macro. Implicacao: analise fundamentalista tambem nao gera alfa consistente. A forma forte: precos refletem ate informacao privada. Essa foi empiricamente rejeitada — insider trading funciona, e por isso e ilegal.")
    fala(doc, "Agora a pergunta que voces devem estar se fazendo: se os mercados sao eficientes, por que estamos aqui tentando construir uma estrategia que gera alfa? Resposta: a HME e uma aproximacao util, mas nao e perfeita. E e exatamente nas imperfeicoes que vivem as anomalias de mercado.")

    div(doc)
    h1(doc, "PARTE 3 — ANOMALIAS E FACTOR INVESTING")
    tempo(doc, "0:35 – 0:55  |  Fatores, anomalias e momentum")
    div(doc)

    acao(doc, "Avancar para o slide 9: Anomalias de Mercado")
    h2(doc, "Anomalias de Mercado")
    fala(doc, "Decadas de pesquisa academica identificaram padroes sistematicos de retorno que contradizem a HME em sua forma semi-forte. A gente chama esses padroes de anomalias ou fatores.")
    fala(doc, "Os cinco mais documentados sao: size — small caps batem large caps no longo prazo, documentado por Banz em 1981. Value — acoes baratas, medidas por P/B ou P/L baixo, batem acoes caras. Formalizado por Fama e French em 1993. Momentum — nossa estrategia — vencedores recentes continuam vencendo. Jegadeesh e Titman, 1993. Quality — empresas lucrativas e de baixa alavancagem batem empresas ruins. E Low Volatility — acoes menos volateis batem as mais volateis, o que e um paradoxo para o CAPM.")
    fala(doc, "O que e interessante e que esses fatores persistem mesmo apos a publicacao academica. Se os mercados fossem perfeitos, publicar uma anomalia a eliminaria — porque todos tentariam explora-la. Mas na pratica os fatores persistem por decadas. Isso sugere que ha alguma explicacao estrutural — seja risco real, seja comportamento sistematico dos investidores.")

    acao(doc, "Avancar para o slide 10: Factor Investing")
    h2(doc, "Factor Investing")
    fala(doc, "Factor investing — ou smart beta — e a abordagem de construir portfolios expostos a esses fatores de forma sistematica e transparente. Em vez de escolher acoes na base do feeling ou da analise individual, voce implementa uma regra clara e replicavel.")
    fala(doc, "A evolucao historica e assim: nos anos 60, o CAPM dizia que so o mercado importava como fator. Em 1993, Fama e French adicionaram size e value — o modelo de tres fatores. Em 1997, Carhart adicionou momentum — o modelo de quatro fatores que ainda e muito usado hoje. Em 2015, Fama e French lancaram o modelo de cinco fatores, adicionando lucratividade e investimento.")
    fala(doc, "Hoje, com machine learning e dados alternativos, a fronteira avan pou muito mais. Mas o nucleo continua sendo esses fatores classicos — e e neles que o Desafio Itau quer ver fundamento.")
    fala(doc, "Uma pergunta natural: por que esses fatores funcionam? A literatura tem tres explicacoes nao-excludentes. Primeiro: risco compensado. O fator representa risco economico real — small caps sao mais iliquidas, empresas value tem mais risco de distress. Segundo: comportamento. Investidores sistematicamente cometem os mesmos erros cognitivos, criando padroes exploraveis. Terceiro: friccoes estruturais. Restricoes institucionais — como restricoes de alavancagem, benchmark tracking — criam oportunidades que persistem.")
    fala(doc, "Nossa estrategia usa o fator momentum. Vamos entender agora por que ele existe e o que a academia diz sobre ele.")

    div(doc)
    h1(doc, "PARTE 4 — O EFEITO MOMENTUM E BEHAVIORAL FINANCE")
    tempo(doc, "0:55 – 1:20  |  A nossa tese de investimento")
    div(doc)

    acao(doc, "Avancar para o slide 11: O Efeito Momentum")
    h2(doc, "O Efeito Momentum")
    fala(doc, "Em 1993, Narasimhan Jegadeesh e Sheridan Titman publicaram um paper que e a pedra angular da nossa estrategia: 'Returns to Buying Winners and Selling Losers'. O resultado central: comprar as acoes que mais subiram nos ultimos 12 meses e vender as que mais caíram gera retorno anormal e estatisticamente significativo nos proximos 3 a 12 meses.")
    fala(doc, "Isso contraria diretamente a forma semi-forte da HME — porque o historico de retornos e informacao publica. Se os mercados fossem perfeitamente eficientes, esse padrao nao deveria existir.")
    fala(doc, "O sinal que eles documentaram e o que ficou conhecido como 12-1: retorno acumulado dos ultimos 12 meses excluindo o mais recente. Por que excluir o ultimo mes? Porque existe um efeito de reversao de curto prazo — o mes mais recente frequentemente reverte. Isso e causado por frictions de microestrutura de mercado: bid-ask spread, liquidez momentanea.")
    fala(doc, "O resultado foi replicado por Rouwenhorst em 1998 em 12 paises europeus — mesmo sinal, mesmo resultado. Por Asness, Moskowitz e Pedersen em 2013, mostrando que funciona em acoes, bonds, moedas e commodities simultaneamente. E em 2023, Hou e colaboradores confirmaram que o momentum sobrevive a toda a critica de replication crisis que varreu o campo de financas comportamentais.")
    fala(doc, "Retorno bruto historico nos EUA: cerca de 1% ao mes. Antes de custos. No Brasil, a literatura academica — Mussa et al., 2012, na Revista de Contabilidade e Financas — encontrou resultado similar para o periodo 1995-2008.")

    acao(doc, "Avancar para o slide 12: Behavioral Finance")
    h2(doc, "Por que o Momentum Existe? — Behavioral Finance")
    fala(doc, "Se o momentum existe e persiste, por que nao e arbitrado? Por que investidores nao exploram isso ate o ponto em que deixa de funcionar? A resposta esta na behavioral finance — financas comportamentais.")
    fala(doc, "Tres mecanismos principais foram propostos pela literatura.")
    fala(doc, "Primeiro: underreaction a noticias. Hong e Stein em 1999 propuseram um modelo com dois tipos de agentes. Os 'newswatchers' processam informacao fundamental mas nao observam o historico de precos. Os 'momentum traders' observam precos mas nao processam todo o fundamental. Nenhum grupo processa toda a informacao disponivel. Resultado: boas noticias sao gradualmente incorporadas ao preco ao longo de meses, gerando uma tendencia persistente.")
    fala(doc, "Segundo: o efeito disposicao. Kahneman e Tversky em 1979 mostraram com a Prospect Theory que as pessoas sentem a dor de uma perda com muito mais intensidade do que o prazer de um ganho equivalente. Na pratica: investidores tendem a vender acoes que subiram cedo demais — 'travar lucro' — e segurar acoes que caíram esperando recuperar. Isso cria oferta precoce nos vencedores, mantendo-os subprecificados por mais tempo.")
    fala(doc, "Terceiro: herding. Gestores institucionais imitam uns aos outros por risco reputacional. Desviar do consenso e arriscado para a carreira — se todo mundo esta errado junto, ninguem e demitido individualmente. Capital flui para vencedores recentes de forma auto-reforcada. Isso cria tendencias que vao alem do fundamento e eventualmente revertem — explicando a reversao de longo prazo de De Bondt e Thaler de 1985.")
    fala(doc, "O ponto critico: esses mecanismos nao desaparecem so porque os academicos os publicaram. Eles sao radicados em como o cerebro humano funciona — vieses cognitivos que se manifestam da mesma forma em traders de Wall Street e em investidores de varejo. E e exatamente ai que a nossa estrategia sistematica tem uma vantagem: ela nao tem emocoes.")

    acao(doc, "Avancar para o slide 13: Momentum no Brasil")
    h2(doc, "Momentum no Brasil")
    fala(doc, "Uma pergunta legitima e: e no Brasil? O IBOVESPA tem particularidades que podem afetar o funcionamento do momentum.")
    fala(doc, "Primeiro: o universo e pequeno. Temos em torno de 80 acoes no indice, contra mais de 3.000 nos EUA. Isso significa que a nossa analise estatistica tem menos graus de liberdade, e precisamos ser mais cautelosos com significancia estatistica.")
    fala(doc, "Segundo: o macro e muito mais volatil. A Selic, o cambio, o risco politico — tudo isso afeta o mercado com uma intensidade muito maior do que nos paises desenvolvidos. A literatura brasileira, como Croteu et al. em 2019, encontrou que o momentum e mais fraco em periodos de alta volatilidade macro — as crises de 2002, 2008 e 2014-2016.")
    fala(doc, "Terceiro: custos de transacao mais altos. Corretagem, taxa da B3, imposto de renda sobre ganhos de capital. Isso significa que um backtest sem custos e muito enganoso — e e por isso que na Aula 8 a gente vai modelar custos explicitamente.")
    fala(doc, "Mas o resultado qualitativo da literatura brasileira, especialmente Mussa et al. de 2012, e claro: o efeito existe. A magnitude e similar a internacional. Mas a volatilidade do alpha e maior, o que exige gestao de risco mais rigorosa.")

    div(doc)
    h1(doc, "PARTE 5 — O DESAFIO ITAU E NOSSA ESTRATEGIA")
    tempo(doc, "1:20 – 1:40  |  Contexto da competicao e o que vamos construir")
    div(doc)

    acao(doc, "Avancar para o slide 14: O Desafio Itau")
    h2(doc, "O Desafio Quant AI — Itau Asset Management")
    fala(doc, "O Desafio Quant AI e uma competicao universitaria patrocinada pela Itau Asset Management — uma das maiores gestoras do Brasil, com mais de 700 bilhoes de reais sob gestao. O objetivo e desenvolver uma estrategia quantitativa completa e defende-la para um juri de profissionais seniors da industria.")
    fala(doc, "Os criterios de avaliacao, conforme o regulamento, tem seis dimensoes. A tese de investimento vale 20% — e a nossa hipotese economica clara e embasada em referencias academicas primarias. Dados e metodologia valem 20% — qualidade da coleta, limpeza e ausencia de look-ahead bias. Rigor do backtest vale 20% — walk-forward, custos reais, multiplos cenarios. Resultados valem 15%. Analise de risco vale 15%. E comunicacao — relatorio e defesa oral — vale 10%.")
    fala(doc, "Reparem que 40% da nota vem de metodologia e rigor de backtest. O juri nao esta so olhando o Sharpe da estrategia — esta olhando se a equipe sabe o que esta fazendo. Uma estrategia com Sharpe mediocre mas metodologia perfeita pode ganhar de uma estrategia com Sharpe alto mas backtest contaminado.")
    fala(doc, "Isso muda como a gente pensa sobre o intensivao. O objetivo nao e ter o maior Sharpe da amostra — e ter a estrategia mais defensavel.")

    acao(doc, "Avancar para o slide 15: Nossa Estrategia")
    h2(doc, "Nossa Estrategia — Momentum Cross-Sectional no IBOVESPA")
    fala(doc, "Entao aqui esta o que vamos construir. Nosso universo: as cerca de 77 acoes constituintes do IBOVESPA, coletadas via yfinance com sufixo .SA. Periodo: 2014 a 2024, dez anos de historico.")
    fala(doc, "O sinal: retorno acumulado dos ultimos 11 meses excluindo o mes mais recente. Em pandas: ret_mensais.shift(2).rolling(11).sum(). Isso e o sinal 12-1 que Jegadeesh e Titman documentaram.")
    fala(doc, "O portfolio: top 10 acoes por sinal, long-only. Versao 1: equal-weight. Versao 2: pesos proporcionais ao sinal ajustado por volatilidade.")
    fala(doc, "Rebalanceamento mensal. Custos modelados em quatro cenarios: 0%, 0.3%, 0.5% e 1% por turno. Walk-forward com 48 meses de treino e 12 de teste.")
    fala(doc, "Cada uma dessas decisoes tem fundamento — e voces vao ser capazes de defender cada uma delas ao juri.")

    acao(doc, "Avancar para o slide 16: Roadmap")
    h2(doc, "Roadmap das 10 Aulas")
    fala(doc, "Aqui esta o mapa do que vamos construir. Aula 1 e hoje — fundamentos. Aula 2: coleta e limpeza de dados. Aula 3: analise exploratoria. Aula 4: construir o sinal v1. Aula 5: primeiro backtest completo. Aula 6: esquemas de alocacao. Aula 7: sinal v2 ajustado por volatilidade. Aula 8: backtest rigoroso — a aula mais importante para o juri. Aula 9: usar GenAI para acelerar a analise. Aula 10: relatorio final e preparacao para a defesa.")
    fala(doc, "Cada aula entrega um parquet — um arquivo de dados — que a proxima aula consome. No final do intensivao, voces tem uma pipeline completa e reprodutivel.")

    div(doc)
    h1(doc, "PARTE 6 — LIVE CODING: SETUP E EXPLORACAO")
    tempo(doc, "1:40 – 2:00  |  Configurar ambiente, explorar estrutura do projeto")
    div(doc)

    fala(doc, "Agora vamos ao computador. Abram o terminal.")
    acao(doc, "Compartilhar tela — abrir terminal")
    fala(doc, "O primeiro passo e clonar o repositorio do intensivao. Digitem:")
    cod(doc, "git clone https://github.com/fmaldonadoo/intensivao-quant-ai.git")
    cod(doc, "cd intensivao-quant-ai")
    fala(doc, "Agora instalem as dependencias. Eu recomendo criar um ambiente virtual primeiro:")
    cod(doc, "python -m venv venv")
    cod(doc, "# Windows: venv\\Scripts\\activate")
    cod(doc, "# Mac/Linux: source venv/bin/activate")
    cod(doc, "pip install yfinance pandas numpy scipy matplotlib seaborn anthropic")
    fala(doc, "Enquanto instala, vamos explorar a estrutura de pastas.")
    acao(doc, "Abrir explorador de arquivos ou digitar 'ls aulas/'")
    fala(doc, "Cada pasta de aula tem um notebook .ipynb e um arquivo de slides .pptx. A pasta dados/ — que ainda esta vazia — vai ser preenchida conforme formos avancando nas aulas. Os parquets que cada aula gera ficam la.")
    fala(doc, "Abram o notebook da Aula 1: aulas/aula-01-kickoff/aula-01-kickoff.ipynb")
    acao(doc, "Abrir o notebook no Jupyter")
    fala(doc, "Percorram as celulas do notebook. A Aula 1 nao tem muito codigo — e principalmente markdown explicando os conceitos que acabamos de discutir, com algumas visualizacoes simples. Na proxima aula a gente comeca valer.")
    fala(doc, "Uma coisa importante: tentem rodar todas as celulas em ordem. Se alguma celula der erro, e sinal de que alguma dependencia nao esta instalada. Avisem no grupo do WhatsApp do intensivao que a gente resolve.")

    div(doc)
    h1(doc, "FECHAMENTO DA AULA 1")
    tempo(doc, "1:55 – 2:00")
    div(doc)
    fala(doc, "Pessoal, e isso para a Aula 1. Hoje a gente construiu a base teorica: entendemos as classes de ativos, a teoria de portfolio, a hipotese de mercados eficientes, o que sao anomalias e fatores, e o efeito momentum com sua justificativa comportamental.")
    fala(doc, "Para a proxima semana: instalem tudo, clonem o repositorio, rodem o notebook da Aula 1. Na Aula 2 vamos comecar a colocar a mao na massa de verdade — coletar os dados de todas as acoes do IBOVESPA e construir o pipeline de dados que vai servir de base para o restante do intensivao.")
    fala(doc, "Alguma duvida antes de encerrar?")
    acao(doc, "Esperar perguntas — responder — encerrar a aula")

    pasta = os.path.join(BASE, "aula-01-kickoff")
    doc.save(os.path.join(pasta, "roteiro-aula-01-kickoff.docx"))
    print("  Aula 01: roteiro salvo -> aula-01-kickoff/")


# ══════════════════════════════════════════════════════════════
# AULA 02 — DADOS
# ══════════════════════════════════════════════════════════════
def aula02():
    doc = novo_doc("02", "Dados: Coleta, Limpeza e Pipeline")

    h1(doc, "ABERTURA")
    tempo(doc, "0:00 – 0:05  |  Recap e contexto da aula")
    div(doc)
    fala(doc, "Pessoal, bem-vindos a Aula 2. Na semana passada a gente construiu a base conceitual — entendemos por que momentum existe e o que queremos construir. Hoje a gente bota a mao na massa de verdade: vamos coletar dados, limpar e construir o pipeline que todas as proximas aulas vao usar.")
    fala(doc, "Uma coisa que quero deixar clara logo no inicio: a qualidade dos dados e a parte mais subestimada de qualquer estrategia quant. Nao e a parte mais glamourosa — mas e onde a maioria dos erros acontece. Dados ruins geram backtests errados que geram conclusoes erradas. A gente vai ser obsessivos com qualidade aqui.")

    div(doc)
    h1(doc, "PARTE 1 — TEORIA (30 min)")
    tempo(doc, "0:05 – 0:30")
    div(doc)

    acao(doc, "Avancar para slide 3: O IBOVESPA")
    h2(doc, "O IBOVESPA — Nosso Universo de Ativos")
    fala(doc, "O IBOVESPA e o principal indice de acoes do Brasil. Ele e composto pelas acoes mais liquidas da B3 — a bolsa brasileira. A composicao e revisada a cada quatro meses — em janeiro, maio e setembro — com base em criterios de liquidez.")
    fala(doc, "Para ser incluida no indice, uma acao precisa ter sido negociada em pelo menos 95% dos pregoes do periodo de apuracao, ter uma participacao minima no volume financeiro total da bolsa, e o preco nao pode ser menor que R$1 — o que excluiria penny stocks.")
    fala(doc, "Hoje o IBOVESPA tem em torno de 77 a 80 acoes. Esse numero varia com cada revisao. Para o nosso backtest, vamos usar uma lista de tickers que representa as acoes historicamente mais relevantes do indice.")
    fala(doc, "Um ponto importante: a gente vai ter um problema chamado survivorship bias — vies de sobrevivencia. Como a gente usa a composicao atual do indice como proxy do universo historico, acabamos ignorando acoes que existiam no passado mas que saíram do indice — geralmente porque foram mal e perderam liquidez. Isso tende a inflar artificialmente os resultados do backtest.")
    fala(doc, "Para o contexto do Desafio Itau, essa simplificacao e aceitavel — mas voces precisam mencionar essa limitacao no relatorio. Em um contexto profissional real, usariamos uma base point-in-time, como a Compustat ou Refinitiv, que tem a composicao historica exata do indice.")

    acao(doc, "Avancar para slide 4: Qualidade de Dados")
    h2(doc, "Qualidade de Dados Financeiros")
    fala(doc, "Dados financeiros brutos raramente estao prontos para uso direto. Ha quatro tipos principais de problemas que a gente precisa tratar.")
    fala(doc, "Primeiro: missing values. Dados ausentes acontecem quando uma acao foi suspensa de negociacao, quando houve feriado local em uma praca especifica, ou simplesmente quando a API do Yahoo Finance falhou naquele dia. A estrategia de tratamento depende do tipo de ausencia. Para falhas curtas — menos de 5 dias — usamos forward fill: propagamos o ultimo valor disponivel. Para ausencias longas — mais de 20% do periodo — e melhor remover a acao completamente daquele periodo.")
    fala(doc, "Segundo: ajustes corporativos. Isso e muito importante. Quando uma empresa faz um split — digamos, 1 acao vira 3 — o preco divide por 3 instantaneamente. Se voce usa o preco sem ajuste, parece que a acao caiu 67% em um dia, o que e um outlier absurdo. O yfinance ja resolve isso: ao usar auto_adjust=True, ele retorna o Adjusted Close, que incorpora todos os splits e dividendos historicamente.")
    fala(doc, "Terceiro: outliers. Mesmo com dados ajustados, voce vai encontrar retornos de +200% ou -80% em um mes. Na maioria dos casos, isso e erro de dado — um ajuste corporativo nao processado corretamente, um ticker errado, um dado de teste que escorregou para producao. Voce precisa filtrar e inspecionar manualmente cada outlier antes de decidir o que fazer.")
    fala(doc, "Quarto: o formato do dado. yfinance retorna dados em formato wide — colunas sao os tickers, linhas sao as datas. Ja e o formato que queremos para a maioria das operacoes do pandas.")

    acao(doc, "Avancar para slide 5: Pipeline")
    h2(doc, "Pipeline de Dados e Formato Parquet")
    fala(doc, "A ideia do pipeline e simples: rodar uma vez, usar para sempre. O notebook da Aula 2 e o unico que acessa a internet para baixar dados. Todos os outros notebooks vao ler os parquets que geramos hoje.")
    fala(doc, "Por que parquet e nao CSV? Tres razoes principais. Velocidade: um parquet com 10 anos de dados de 77 acoes carrega em menos de 1 segundo. Um CSV equivalente leva 10 a 30 segundos e ainda pode ter problemas de parse. Tipos: o parquet preserva os tipos de dados — datetime64, float64 — automaticamente. Com CSV, o pandas precisa inferir os tipos na leitura, o que as vezes erra. E tamanho: com compressao snappy, o parquet e tipicamente 5 a 10 vezes menor que o CSV equivalente.")

    div(doc)
    h1(doc, "PARTE 2 — LIVE CODING (90 min)")
    tempo(doc, "0:30 – 2:00")
    div(doc)

    acao(doc, "Abrir notebook: aulas/aula-02-dados/aula-02-dados.ipynb")
    fala(doc, "Abram o notebook da Aula 2. Vamos percorrer cada celula juntos.")

    h2(doc, "Bloco 1 — Importacoes e Configuracao")
    fala(doc, "A primeira celula importa as bibliotecas. Vou digitar e explicar cada uma.")
    cod(doc, "import pandas as pd")
    fala(doc, "Pandas e nossa ferramenta principal de manipulacao de dados. DataFrames, Series, operacoes em vetores — tudo passa por aqui.")
    cod(doc, "import numpy as np")
    fala(doc, "Numpy e a base matematica — operacoes numericas rapidas em arrays.")
    cod(doc, "import yfinance as yf")
    fala(doc, "yfinance e nossa fonte de dados. E uma biblioteca Python que acessa a API do Yahoo Finance — gratuita e com historico de acoes do mundo todo, incluindo a B3.")
    cod(doc, "import matplotlib.pyplot as plt")
    cod(doc, "import warnings")
    cod(doc, "warnings.filterwarnings('ignore')")
    cod(doc, "pd.set_option('display.max_columns', 20)")

    h2(doc, "Bloco 2 — Lista de Tickers do IBOVESPA")
    fala(doc, "Agora definimos o universo de acoes. Essa lista representa as principais acoes que compuseram o IBOVESPA no nosso periodo de analise.")
    cod(doc, "TICKERS_IBOV = [")
    cod(doc, "    'PETR4.SA', 'VALE3.SA', 'ITUB4.SA', 'BBDC4.SA', 'B3SA3.SA',")
    cod(doc, "    'ABEV3.SA', 'WEGE3.SA', 'RENT3.SA', 'RADL3.SA', 'MGLU3.SA',")
    cod(doc, "    # ... lista completa no notebook")
    cod(doc, "]")
    fala(doc, "O sufixo .SA indica que sao acoes negociadas na bolsa brasileira. Sem o sufixo, o yfinance tentaria buscar no mercado americano.")
    fala(doc, "No notebook vocês vão ver a lista completa com todas as 77 acoes. Eu nao vou digitar todas aqui — mas quero que voces entendam o criterio: sao as acoes com maior historico de presenca no IBOVESPA no periodo 2014-2024.")

    h2(doc, "Bloco 3 — Download dos Dados")
    fala(doc, "Agora a parte que acessa a internet. Vamos usar yf.download.")
    cod(doc, "DATA_INICIO = '2012-01-01'  # 2 anos antes para warm-up do sinal")
    cod(doc, "DATA_FIM    = '2024-12-31'")
    cod(doc, "")
    cod(doc, "print(f'Baixando {len(TICKERS_IBOV)} acoes de {DATA_INICIO} a {DATA_FIM}...')")
    cod(doc, "df_raw = yf.download(")
    cod(doc, "    TICKERS_IBOV,")
    cod(doc, "    start=DATA_INICIO,")
    cod(doc, "    end=DATA_FIM,")
    cod(doc, "    auto_adjust=True,")
    cod(doc, "    progress=False")
    cod(doc, ")")
    fala(doc, "Reparem no auto_adjust=True. Esse parametro garante que o preco retornado ja esta ajustado por todos os eventos corporativos historicos — splits, dividendos, inplits. Se voce usar False, precisa fazer esse ajuste manualmente.")
    fala(doc, "Tambem estamos comeando em 2012 mesmo que nosso backtest seja a partir de 2014. Por que? Porque o sinal momentum 12-1 precisa de 13 meses de historico para calcular o primeiro valor. Entao precisamos de um periodo de warm-up antes de comecar a tomar decisoes.")
    acao(doc, "Aguardar o download — costuma levar 30 a 60 segundos")
    fala(doc, "Enquanto baixa, se voce ver alguma mensagem de ticker nao encontrado — 'No price data found' — e porque aquela acao nao tinha dados no periodo. Vamos lidar com isso na limpeza.")

    h2(doc, "Bloco 4 — Extrair o Preco de Fechamento Ajustado")
    fala(doc, "O yfinance retorna um DataFrame com varios niveis de coluna. Precisamos extrair so o Close.")
    cod(doc, "# yfinance retorna MultiIndex: (campo, ticker)")
    cod(doc, "# Pegamos apenas o preco de fechamento ajustado")
    cod(doc, "if isinstance(df_raw.columns, pd.MultiIndex):")
    cod(doc, "    precos = df_raw['Close'].copy()")
    cod(doc, "else:")
    cod(doc, "    precos = df_raw.copy()")
    cod(doc, "")
    cod(doc, "print(f'Shape: {precos.shape}')")
    cod(doc, "print(f'Periodo: {precos.index[0].date()} a {precos.index[-1].date()}')")
    cod(doc, "precos.head()")
    fala(doc, "O shape deve ser algo como (3.000 linhas, 77 colunas). 3.000 dias uteis em 12 anos, 77 acoes. Se o numero de colunas for menor, e porque algumas acoes nao tinham dados no comeco do periodo — normal.")

    h2(doc, "Bloco 5 — Limpeza de Dados")
    fala(doc, "Agora a parte critica: limpeza.")
    cod(doc, "def limpar_precos(df, min_pct_valido=0.7):")
    cod(doc, "    '''Remove colunas com dados insuficientes e aplica forward fill'''")
    cod(doc, "    # Calcular % de dados validos por acao")
    cod(doc, "    pct_valido = df.notna().mean()")
    cod(doc, "    acoes_ok = pct_valido[pct_valido >= min_pct_valido].index")
    cod(doc, "    df_filtrado = df[acoes_ok].copy()")
    cod(doc, "    ")
    cod(doc, "    # Forward fill para gaps curtos (max 5 dias)")
    cod(doc, "    df_limpo = df_filtrado.ffill(limit=5)")
    cod(doc, "    ")
    cod(doc, "    print(f'Acoes originais: {df.shape[1]}')")
    cod(doc, "    print(f'Acoes apos filtro: {df_limpo.shape[1]}')")
    cod(doc, "    return df_limpo")
    cod(doc, "")
    cod(doc, "precos_limpos = limpar_precos(precos, min_pct_valido=0.7)")
    fala(doc, "A funcao faz duas coisas. Primeiro: remove acoes que tem menos de 70% dos dados validos — essas nao tem historico suficiente para entrar no backtest. Segundo: aplica forward fill com limite de 5 dias para gaps curtos — um feriado local, por exemplo, dura no maximo 4 dias. Gaps maiores ficam como NaN para tratamento posterior.")
    fala(doc, "Por que 70% como threshold? E uma escolha pragmatica. Menos que isso e voce perde muitas acoes. Mais que isso e voce pode estar excluindo acoes que simplesmente comecaram a ser negociadas mais recentemente.")

    h2(doc, "Bloco 6 — Detectar e Tratar Outliers")
    fala(doc, "Agora vamos calcular os retornos diarios e detectar outliers.")
    cod(doc, "# Calcular retornos diarios")
    cod(doc, "ret_diarios_raw = precos_limpos.pct_change()")
    cod(doc, "")
    cod(doc, "# Detectar outliers: retornos |r| > 50% em um dia")
    cod(doc, "LIMITE_OUTLIER = 0.50")
    cod(doc, "outliers = (ret_diarios_raw.abs() > LIMITE_OUTLIER)")
    cod(doc, "n_outliers = outliers.sum().sum()")
    cod(doc, "print(f'Outliers detectados: {n_outliers}')")
    cod(doc, "")
    cod(doc, "# Substituir outliers por NaN")
    cod(doc, "ret_diarios = ret_diarios_raw.copy()")
    cod(doc, "ret_diarios[outliers] = np.nan")
    fala(doc, "Um retorno diario de mais de 50% e quase certamente um erro de dado — nao uma variacao real de preco. A excecao seriam eventos extremamente raros como recuperacao de uma empresa em default. Inspecionamos manualmente qualquer outlier encontrado antes de decidir o que fazer.")

    h2(doc, "Bloco 7 — Calcular Retornos Mensais")
    fala(doc, "Para o nosso sinal momentum, precisamos de retornos mensais.")
    cod(doc, "def retorno_composto(serie):")
    cod(doc, "    '''Retorno composto de uma serie de retornos diarios'''")
    cod(doc, "    return (1 + serie).prod() - 1")
    cod(doc, "")
    cod(doc, "ret_mensais = (\n    ret_diarios\n    .resample('ME')\n    .apply(retorno_composto)\n)")
    cod(doc, "")
    cod(doc, "print(f'Retornos mensais: {ret_mensais.shape}')")
    cod(doc, "ret_mensais.tail()")
    fala(doc, "O resample ME — Month End — agrega os dados por mes. A funcao retorno_composto calcula o retorno composto: (1+r1) x (1+r2) x ... - 1. Isso e mais preciso do que simplesmente somar os retornos diarios, especialmente em periodos de alta volatilidade.")
    fala(doc, "Reparem que o indice agora sao datas de fim de mes — 31/01, 28/02 etc. E cada valor e o retorno acumulado daquele mes para cada acao.")

    h2(doc, "Bloco 8 — Salvar os Parquets")
    fala(doc, "Agora o passo final: salvar tudo em parquets para as proximas aulas usarem.")
    cod(doc, "import os")
    cod(doc, "os.makedirs('../../dados', exist_ok=True)")
    cod(doc, "")
    cod(doc, "precos_limpos.to_parquet('../../dados/precos_ibov.parquet')")
    cod(doc, "ret_diarios.to_parquet('../../dados/retornos_diarios_limpo.parquet')")
    cod(doc, "ret_mensais.to_parquet('../../dados/retornos_mensais_limpo.parquet')")
    cod(doc, "")
    cod(doc, "print('Parquets salvos:')")
    cod(doc, "for f in ['precos_ibov', 'retornos_diarios_limpo', 'retornos_mensais_limpo']:")
    cod(doc, "    path = f'../../dados/{f}.parquet'")
    cod(doc, "    size_kb = os.path.getsize(path) / 1024")
    cod(doc, "    print(f'  {f}.parquet: {size_kb:.1f} KB')")
    fala(doc, "Tres arquivos gerados. precos_ibov.parquet tem os precos diarios ajustados. retornos_diarios_limpo.parquet tem os retornos diarios calculados e com outliers removidos. retornos_mensais_limpo.parquet tem os retornos mensais compostos.")
    fala(doc, "Esses tres arquivos sao a materia-prima de todo o restante do intensivao. A partir da Aula 3, nenhum notebook vai mais acessar a internet ou o yfinance — tudo vem desses parquets.")

    h2(doc, "Bloco 9 — Verificacao de Sanidade")
    fala(doc, "Antes de encerrar, vamos fazer um check de sanidade dos dados.")
    cod(doc, "print('=== CHECK DE SANIDADE ===')")
    cod(doc, "print(f'Periodo: {ret_mensais.index[0].date()} a {ret_mensais.index[-1].date()}')")
    cod(doc, "print(f'Numero de acoes: {ret_mensais.shape[1]}')")
    cod(doc, "print(f'Numero de meses: {ret_mensais.shape[0]}')")
    cod(doc, "print(f'% de dados validos: {ret_mensais.notna().mean().mean():.1%}')")
    cod(doc, "print()")
    cod(doc, "print('Estatisticas basicas (retornos mensais):')")
    cod(doc, "print(ret_mensais.stack().describe())")
    fala(doc, "O que eu espero ver aqui: media de retorno mensal por volta de 1-2%, desvio padrao em torno de 8-12%, percentil 1% em torno de -25% e percentil 99% em torno de +30%. Esses valores sao coerentes com o que sabemos sobre o mercado brasileiro.")
    fala(doc, "Se voces virem algo muito fora disso — como media negativa muito grande ou desvio padrao superior a 20% — e sinal de que ainda tem dado sujo. Nao sigam para a Aula 3 sem resolver isso.")

    div(doc)
    h1(doc, "FECHAMENTO DA AULA 2")
    tempo(doc, "1:55 – 2:00")
    div(doc)
    fala(doc, "Pessoal, excelente trabalho hoje. A gente construiu o pipeline de dados do intensivao. Tres parquets limpos, prontos para uso.")
    fala(doc, "Para a proxima aula: confiram que os tres parquets foram gerados na pasta dados/. Tentem carregar cada um com pd.read_parquet e verificar o shape. Se der qualquer erro, me avisem.")
    fala(doc, "Na Aula 3 vamos fazer a analise exploratoria — entender a distribuicao dos retornos, as correlacoes, e o que os dados nos dizem sobre o mercado brasileiro antes de comecarmos a construir qualquer sinal.")

    pasta = os.path.join(BASE, "aula-02-dados")
    doc.save(os.path.join(pasta, "roteiro-aula-02-dados.docx"))
    print("  Aula 02: roteiro salvo -> aula-02-dados/")


# ══════════════════════════════════════════════════════════════
# AULA 03 — EDA
# ══════════════════════════════════════════════════════════════
def aula03():
    doc = novo_doc("03", "EDA: Analise Exploratoria dos Retornos")

    h1(doc, "ABERTURA")
    tempo(doc, "0:00 – 0:05")
    div(doc)
    fala(doc, "Bem-vindos a Aula 3. Na semana passada a gente coletou e limpou os dados — temos tres parquets prontos. Hoje vamos fazer o EDA: Exploratory Data Analysis. Isso significa olhar para os dados com curiosidade antes de tomar qualquer decisao.")
    fala(doc, "Parece uma etapa burocratica? Nao e. O EDA e onde voce descobre os problemas que o pipeline de limpeza nao pegou, os padroes que vao guiar as decisoes de design da estrategia, e as armadilhas que poderiam sabotar o backtest. Nunca pule o EDA.")

    div(doc)
    h1(doc, "PARTE 1 — TEORIA (25 min)")
    tempo(doc, "0:05 – 0:30")
    div(doc)

    acao(doc, "Avancar slide 3: Distribuicao de Retornos")
    h2(doc, "Fat Tails — Por que a Gaussiana Falha")
    fala(doc, "A base de quase toda a teoria financeira classica — CAPM, Black-Scholes, Value-at-Risk gaussiano — assume que retornos sao normalmente distribuidos. Isso e uma mentira conveniente. E uma mentira que pode ser muito cara.")
    fala(doc, "Retornos financeiros tem o que chamamos de fat tails — caudas pesadas. Em uma distribuicao normal, um retorno de 3 desvios-padrao acontece em 0.3% dos dias — ou seja, menos de 1 vez por ano. Na realidade dos mercados, retornos extremos acontecem muito mais frequentemente.")
    fala(doc, "Benoit Mandelbrot — o pai dos fractais — ja documentou isso em 1963 para o mercado de algodao nos EUA. Nassim Taleb popularizou o conceito com o 'Cisne Negro'. A intuicao e simples: os mercados sao sistemas complexos com feedback e cascata de informacoes, nao lancamentos de dados independentes.")
    fala(doc, "A metrica quantitativa e a curtose em excesso. A distribuicao normal tem curtose 3 — ou 0 em excesso. Dados financeiros tipicamente tem curtose em excesso de 3 a 10. Isso significa que a probabilidade de eventos extremos e muito maior do que a gaussiana preve.")
    fala(doc, "A skewness — assimetria — tambem e importante. Retornos de acoes tipicamente tem skewness negativa: quedas sao maiores que altas em magnitude. O mercado cai mais rapido do que sobe — um fato estilizado bem documentado.")
    fala(doc, "Por que isso importa para nos? Porque o Sharpe Ratio assume normalidade. Em dados com fat tails e skewness negativa, o Sharpe subestima o risco real. E por isso que vamos reportar tambem Sortino — que penaliza so os retornos negativos — e o Max Drawdown, que captura o pior cenario.")

    acao(doc, "Avancar slide 4: Correlacoes e Estacionariedade")
    h2(doc, "Correlacoes e Estacionariedade")
    fala(doc, "Correlacoes entre acoes sao dinamicas — mudam com o tempo e com o regime de mercado. Em periodos normais, a correlacao media entre acoes do IBOVESPA fica em torno de 0.40 a 0.50. Em crises — 2008, 2020 — essa correlacao pode subir para 0.80 ou mais.")
    fala(doc, "Isso e critico para entender a diversificacao. Quando mais voce precisa de diversificacao — em uma crise — e exatamente quando ela falha. Ativos que pareciam descorrelacionados em tempos normais caem juntos quando ha stress.")
    fala(doc, "Para o nosso portfolio momentum, isso significa que em crises, mesmo selecionando os melhores do universo, podemos estar todos altamente correlacionados porque o mercado todo cai junto. E uma limitacao real da estrategia que precisa aparecer no relatorio.")
    fala(doc, "Sobre estacionariedade: precos de acoes sao series temporais nao-estacionarias. A media e a variancia mudam com o tempo — ha uma tendencia estrutural de alta. Isso torna qualquer analise estatistica diretamente sobre precos espuria — o que se chama de regressao espuria.")
    fala(doc, "Retornos, por outro lado, sao aproximadamente estacionarios. A media e estavel em torno de um valor positivo pequeno, e a variancia nao explode ao longo do tempo. O teste formal e o teste ADF — Augmented Dickey-Fuller. Retornos tipicamente rejeitam a hipotese nula de raiz unitaria com p-value muito baixo; precos tipicamente nao rejeitam.")
    fala(doc, "Regra pratica: NUNCA modele precos diretamente. Sempre transforme em retornos primeiro.")

    div(doc)
    h1(doc, "PARTE 2 — LIVE CODING (90 min)")
    tempo(doc, "0:30 – 2:00")
    div(doc)

    acao(doc, "Abrir notebook: aulas/aula-03-eda/aula-03-eda.ipynb")

    h2(doc, "Bloco 1 — Carregar Dados")
    fala(doc, "Comecamos carregando os parquets da Aula 2.")
    cod(doc, "import pandas as pd")
    cod(doc, "import numpy as np")
    cod(doc, "import matplotlib.pyplot as plt")
    cod(doc, "import seaborn as sns")
    cod(doc, "from scipy import stats")
    cod(doc, "")
    cod(doc, "ret_diarios  = pd.read_parquet('../../dados/retornos_diarios_limpo.parquet')")
    cod(doc, "ret_mensais  = pd.read_parquet('../../dados/retornos_mensais_limpo.parquet')")
    cod(doc, "")
    cod(doc, "print('Retornos diarios:', ret_diarios.shape)")
    cod(doc, "print('Retornos mensais:', ret_mensais.shape)")
    fala(doc, "Rapido check: o shape deve ser coerente com o que geramos na Aula 2. Se os numeros nao batem, algo deu errado no pipeline — voltem ao notebook 2 e verifiquem.")

    h2(doc, "Bloco 2 — Estatisticas Descritivas")
    fala(doc, "Primeiro: estatisticas basicas dos retornos mensais.")
    cod(doc, "# Retornos mensais empilhados — todas as acoes, todos os meses")
    cod(doc, "ret_stack = ret_mensais.stack().dropna()")
    cod(doc, "")
    cod(doc, "print('=== ESTATISTICAS RETORNOS MENSAIS ===')")
    cod(doc, "print(f'Media:        {ret_stack.mean():.3%}')")
    cod(doc, "print(f'Mediana:      {ret_stack.median():.3%}')")
    cod(doc, "print(f'Desvio Pad.:  {ret_stack.std():.3%}')")
    cod(doc, "print(f'Skewness:     {ret_stack.skew():.3f}')")
    cod(doc, "print(f'Curtose exc.: {ret_stack.kurtosis():.3f}')")
    cod(doc, "print(f'Minimo:       {ret_stack.min():.3%}')")
    cod(doc, "print(f'Maximo:       {ret_stack.max():.3%}')")
    fala(doc, "O que espero ver: media em torno de 1.5-2% ao mes, desvio padrao de 10-12%, skewness negativa — digamos -0.3 a -0.8 — e curtose em excesso bem acima de zero — provavelmente entre 2 e 8.")
    fala(doc, "Se a skewness for muito negativa — abaixo de -1 — pode ser sinal de que ainda tem outliers. Se a curtose for acima de 15, mesma coisa.")

    h2(doc, "Bloco 3 — Histograma e QQ-Plot")
    fala(doc, "Agora a visualizacao. Quero ver a distribuicao empirica versus a gaussiana.")
    cod(doc, "fig, axes = plt.subplots(1, 2, figsize=(14, 5))")
    cod(doc, "")
    cod(doc, "# Histograma")
    cod(doc, "ax = axes[0]")
    cod(doc, "ret_stack.hist(bins=80, density=True, alpha=0.7, color='steelblue', ax=ax)")
    cod(doc, "x = np.linspace(ret_stack.min(), ret_stack.max(), 300)")
    cod(doc, "ax.plot(x, stats.norm.pdf(x, ret_stack.mean(), ret_stack.std()),")
    cod(doc, "        'r-', lw=2, label='Normal')")
    cod(doc, "ax.set_title('Distribuicao dos Retornos Mensais')")
    cod(doc, "ax.set_xlabel('Retorno Mensal'); ax.legend()")
    cod(doc, "")
    cod(doc, "# QQ-Plot")
    cod(doc, "ax2 = axes[1]")
    cod(doc, "stats.probplot(ret_stack, dist='norm', plot=ax2)")
    cod(doc, "ax2.set_title('QQ-Plot: Retornos vs Normal')")
    cod(doc, "plt.tight_layout()")
    cod(doc, "plt.savefig('distribuicao_retornos.png', dpi=150, bbox_inches='tight')")
    cod(doc, "plt.show()")
    fala(doc, "Olhem para o histograma. A curva vermelha e a gaussiana com mesma media e desvio padrao. Voces vao ver que a distribuicao empirica tem pico mais alto — mais concentrada ao redor da media — e caudas mais gordas — mais eventos extremos do que a normal preve.")
    fala(doc, "No QQ-plot, se os dados fossem normais, os pontos formariam uma linha reta diagonal. Voces vao ver que nas extremidades — nos cantos inferior-esquerdo e superior-direito — os pontos se desviam da linha. Isso e a assinatura visual das fat tails.")

    h2(doc, "Bloco 4 — Retorno vs Risco por Acao")
    fala(doc, "Agora um grafico que e fundamental antes de qualquer estrategia: retorno medio versus risco por acao.")
    cod(doc, "ret_medio = ret_mensais.mean()")
    cod(doc, "vol_mensal = ret_mensais.std()")
    cod(doc, "")
    cod(doc, "fig, ax = plt.subplots(figsize=(12, 7))")
    cod(doc, "ax.scatter(vol_mensal, ret_medio, alpha=0.7, s=60, color='steelblue')")
    cod(doc, "")
    cod(doc, "# Anotar as principais acoes")
    cod(doc, "for ticker in ['PETR4.SA', 'VALE3.SA', 'WEGE3.SA', 'BBAS3.SA']:")
    cod(doc, "    if ticker in ret_medio.index:")
    cod(doc, "        ax.annotate(ticker.replace('.SA',''),")
    cod(doc, "                    (vol_mensal[ticker], ret_medio[ticker]),")
    cod(doc, "                    fontsize=9, ha='left')")
    cod(doc, "ax.set_xlabel('Volatilidade Mensal (desvio padrao)')")
    cod(doc, "ax.set_ylabel('Retorno Medio Mensal')")
    cod(doc, "ax.set_title('Risco x Retorno por Acao — IBOVESPA 2014-2024')")
    cod(doc, "ax.axhline(0, color='gray', lw=0.5)")
    cod(doc, "plt.tight_layout(); plt.savefig('risco_retorno.png', dpi=150); plt.show()")
    fala(doc, "O que voces vao ver nesse grafico? Uma nuvem de pontos sem um padrao claro de relacao entre risco e retorno — o que contradiz a predicao do CAPM de que mais risco implica mais retorno. Isso e consistente com a anomalia de Low Volatility que discutimos na Aula 1.")
    fala(doc, "Algumas acoes no canto superior esquerdo: alto retorno, baixo risco. Sao as acoes que mais queremos no portfolio. Algumas no canto inferior direito: alto risco, baixo retorno. Sao as que mais queremos evitar.")

    h2(doc, "Bloco 5 — Heatmap de Correlacoes")
    fala(doc, "Agora as correlacoes entre as acoes.")
    cod(doc, "# Matriz de correlacao dos retornos mensais")
    cod(doc, "corr = ret_mensais.corr()")
    cod(doc, "")
    cod(doc, "fig, ax = plt.subplots(figsize=(14, 12))")
    cod(doc, "mask = np.triu(np.ones_like(corr, dtype=bool))")
    cod(doc, "sns.heatmap(corr, mask=mask, cmap='RdYlGn', center=0,")
    cod(doc, "            vmin=-0.3, vmax=0.8, square=True,")
    cod(doc, "            xticklabels=[t.replace('.SA','') for t in corr.columns],")
    cod(doc, "            yticklabels=[t.replace('.SA','') for t in corr.index],")
    cod(doc, "            ax=ax)")
    cod(doc, "ax.set_title('Correlacao entre Acoes do IBOVESPA (Retornos Mensais)')")
    cod(doc, "plt.tight_layout(); plt.savefig('heatmap_correlacoes.png', dpi=150); plt.show()")
    cod(doc, "")
    cod(doc, "print(f'Correlacao media: {corr.values[np.tril_indices_from(corr.values, k=-1)].mean():.3f}')")
    fala(doc, "A correlacao media deve ser positiva — em torno de 0.35 a 0.50. Isso faz sentido: todas essas acoes estao expostas ao mercado brasileiro, que move tudo junto. Mas ha variacao significativa: acoes do mesmo setor tem correlacao maior, acoes de setores diferentes tem correlacao menor.")
    fala(doc, "Identifiquem visualmente os clusters setoriais: os grandes bancos — Itau, Bradesco, BB — provavelmente tem correlacao alta entre si. Petroleo e Gas — Petrobras — tem correlacao menor com os bancos.")

    h2(doc, "Bloco 6 — Correlacao Movel")
    fala(doc, "Por fim, quero mostrar que a correlacao nao e estavel no tempo.")
    cod(doc, "# Correlacao media movel — janela de 12 meses")
    cod(doc, "def corr_media_movel(ret, janela=12):")
    cod(doc, "    corrs = []")
    cod(doc, "    for i in range(janela, len(ret)):")
    cod(doc, "        janela_ret = ret.iloc[i-janela:i]")
    cod(doc, "        c = janela_ret.corr().values")
    cod(doc, "        idx = np.tril_indices_from(c, k=-1)")
    cod(doc, "        corrs.append({'data': ret.index[i], 'corr_media': c[idx].mean()})")
    cod(doc, "    return pd.DataFrame(corrs).set_index('data')")
    cod(doc, "")
    cod(doc, "corr_movel = corr_media_movel(ret_mensais, janela=12)")
    cod(doc, "")
    cod(doc, "fig, ax = plt.subplots(figsize=(14, 5))")
    cod(doc, "ax.plot(corr_movel, color='steelblue', lw=1.5)")
    cod(doc, "ax.fill_between(corr_movel.index, corr_movel['corr_media'], alpha=0.2)")
    cod(doc, "ax.axhline(corr_movel.mean().values[0], color='red', ls='--', label='Media')")
    cod(doc, "ax.set_title('Correlacao Media Movel (12 meses)')")
    cod(doc, "ax.set_ylabel('Correlacao Media entre Acoes')")
    cod(doc, "ax.legend(); plt.tight_layout()")
    cod(doc, "plt.savefig('correlacao_movel.png', dpi=150); plt.show()")
    fala(doc, "Esse grafico conta uma historia. Voces vao ver picos de correlacao em momentos de crise — provavelmente em 2015-2016, 2018 e 2020. Nesses momentos, diversificacao dentro do mercado brasileiro quase nao ajuda — tudo cai junto.")
    fala(doc, "Isso reforca um ponto sobre a nossa estrategia: ela e fundamentalmente um portfolio beta do mercado brasileiro. Em crises sistemicas, ela vai sofrer. Nao existe estrategia de acoes que escape disso completamente — e isso precisa estar no nosso relatorio de forma honesta.")

    h2(doc, "Bloco 7 — Teste de Estacionariedade")
    fala(doc, "Por fim, vamos formalizar o ponto sobre estacionariedade com o teste ADF.")
    cod(doc, "from statsmodels.tsa.stattools import adfuller")
    cod(doc, "")
    cod(doc, "# Testar PETR4 como exemplo")
    cod(doc, "ticker_ex = 'PETR4.SA'")
    cod(doc, "preco_ex = pd.read_parquet('../../dados/precos_ibov.parquet')[ticker_ex].dropna()")
    cod(doc, "ret_ex   = ret_diarios[ticker_ex].dropna()")
    cod(doc, "")
    cod(doc, "adf_preco = adfuller(preco_ex, autolag='AIC')")
    cod(doc, "adf_ret   = adfuller(ret_ex,   autolag='AIC')")
    cod(doc, "")
    cod(doc, "print(f'PETR4 — Preco: ADF stat={adf_preco[0]:.3f}, p-value={adf_preco[1]:.4f}')")
    cod(doc, "print(f'PETR4 — Retorno: ADF stat={adf_ret[0]:.3f}, p-value={adf_ret[1]:.4f}')")
    fala(doc, "O resultado vai ser claro: para o preco, o p-value vai ser alto — digamos 0.30 ou mais — o que significa que nao conseguimos rejeitar a hipotese de raiz unitaria. O preco e nao-estacionario.")
    fala(doc, "Para o retorno, o p-value vai ser virtualmente zero — 0.000. Rejeitamos a hipotese de raiz unitaria. O retorno e estacionario. Isso justifica, empiricamente, por que a gente sempre trabalha com retornos e nao com precos.")

    div(doc)
    h1(doc, "FECHAMENTO DA AULA 3")
    tempo(doc, "1:55 – 2:00")
    div(doc)
    fala(doc, "Excelente. Hoje a gente fez a analise exploratoria completa. Os insights principais: retornos tem fat tails — o Sharpe vai subestimar risco. Correlacoes sao dinamicas — em crises, diversificacao falha. E retornos sao estacionarios, precos nao — sempre usar retornos.")
    fala(doc, "Para a proxima aula: revisitem os graficos que geramos hoje. Eles vao aparecer de novo no relatorio final. Na Aula 4, vamos construir o primeiro sinal — o momentum 12-1.")

    pasta = os.path.join(BASE, "aula-03-eda")
    doc.save(os.path.join(pasta, "roteiro-aula-03-eda.docx"))
    print("  Aula 03: roteiro salvo -> aula-03-eda/")


if __name__ == "__main__":
    print("Gerando roteiros das aulas 01, 02, 03...")
    aula01()
    aula02()
    aula03()
    print("Concluido!")
