"""
Gera roteiros DOCX para Aulas 8, 9, 10 do Intensivao Quant AI.
"""
import os
from docx import Document
from docx.shared import Pt, RGBColor, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

NAVY  = RGBColor(0x0D, 0x1B, 0x3E)
GOLD  = RGBColor(0xF5, 0xA6, 0x23)
GREEN = RGBColor(0x1E, 0x8B, 0x4C)
BLUE  = RGBColor(0x1A, 0x6E, 0xAE)
BROWN = RGBColor(0x7B, 0x4F, 0x12)

BASE = os.path.dirname(os.path.abspath(__file__))


def novo_doc(num, titulo):
    doc = Document()
    sec = doc.sections[0]
    sec.page_width  = Inches(8.5)
    sec.page_height = Inches(11)
    sec.top_margin    = Inches(1)
    sec.bottom_margin = Inches(1)
    sec.left_margin   = Inches(1.2)
    sec.right_margin  = Inches(1.2)

    # Cabecalho
    hdr = doc.add_heading("", level=0)
    hdr.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = hdr.add_run(f"INTENSIVAO QUANT AI — AULA {num:02d}")
    run.font.color.rgb = NAVY
    run.font.size = Pt(20)
    run.font.bold = True

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = sub.add_run(titulo.upper())
    r.font.color.rgb = GOLD
    r.font.size = Pt(14)
    r.font.bold = True

    doc.add_paragraph()
    note = doc.add_paragraph()
    note.alignment = WD_ALIGN_PARAGRAPH.CENTER
    rn = note.add_run("ROTEIRO COMPLETO — USO INTERNO DO INSTRUTOR")
    rn.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
    rn.font.size = Pt(9)
    rn.font.italic = True
    doc.add_paragraph()
    return doc


def h1(doc, t):
    p = doc.add_heading("", level=1)
    r = p.add_run(t)
    r.font.color.rgb = NAVY
    r.font.size = Pt(15)
    r.font.bold = True
    return p


def h2(doc, t):
    p = doc.add_heading("", level=2)
    r = p.add_run(t)
    r.font.color.rgb = BLUE
    r.font.size = Pt(12)
    r.font.bold = True
    return p


def fala(doc, t):
    p = doc.add_paragraph()
    r = p.add_run(t)
    r.font.size = Pt(11)
    r.font.color.rgb = RGBColor(0x1A, 0x1A, 0x1A)
    p.paragraph_format.space_after = Pt(6)
    return p


def acao(doc, t):
    p = doc.add_paragraph()
    r = p.add_run(f"[{t}]")
    r.font.size = Pt(10)
    r.font.italic = True
    r.font.color.rgb = BROWN
    p.paragraph_format.space_after = Pt(4)
    return p


def cod(doc, t):
    p = doc.add_paragraph()
    p.paragraph_format.left_indent = Inches(0.4)
    p.paragraph_format.space_after = Pt(4)
    r = p.add_run(t)
    r.font.name = "Courier New"
    r.font.size = Pt(9)
    r.font.color.rgb = BLUE
    return p


def tempo(doc, t):
    p = doc.add_paragraph()
    r = p.add_run(f"[TEMPO: {t}]")
    r.font.size = Pt(10)
    r.font.bold = True
    r.font.color.rgb = GOLD
    p.paragraph_format.space_after = Pt(2)
    return p


def div(doc):
    p = doc.add_paragraph("─" * 60)
    p.paragraph_format.space_before = Pt(6)
    p.paragraph_format.space_after  = Pt(6)
    r = p.runs[0]
    r.font.color.rgb = RGBColor(0xCC, 0xCC, 0xCC)
    r.font.size = Pt(8)


def aula08():
    doc = novo_doc(8, "Backtest Rigoroso e Validacao Estatistica")

    # =========================================================
    h1(doc, "PARTE 1 — TEORIA: O QUE E UM BACKTEST RIGOROSO?")
    tempo(doc, "0:00 – 0:35")
    div(doc)

    h2(doc, "1.1 — O Problema do Backtesting Ingênuo")
    acao(doc, "Slide 1 na tela. Tom sério. Esta aula é a mais importante do curso em termos de rigor científico.")
    fala(doc, "Pessoal, sejam bem-vindos à Aula 8 — Backtest Rigoroso e Validação Estatística.")
    fala(doc, "Nas últimas semanas vocês construíram um pipeline completo: dados, sinal, portfólio, métricas. O backtest mostrou um Sharpe de 0,8, retorno acumulado de mais de 100%. Parece ótimo.")
    fala(doc, "Mas agora vou fazer uma pergunta incômoda: o quanto desse resultado é real, e o quanto é artefato do processo de análise?")
    fala(doc, "Existe um fenômeno muito documentado em finanças quantitativas chamado overfitting — ou ajuste excessivo. Quando você testa muitas hipóteses, muitos parâmetros, muitas variações de um modelo, eventualmente você encontra algo que funcionou no passado simplesmente por acaso estatístico.")
    fala(doc, "É como jogar uma moeda 1.000 vezes e encontrar uma sequência de 10 caras seguidas. Se você olhar só essa sequência e construir uma estratégia baseada nela, vai parecer que a moeda é viesada — mas não é.")
    fala(doc, "Harvey, Liu e Zhu, em um paper de 2016, analisaram centenas de fatores publicados na literatura de finanças e concluíram que a maioria provavelmente são falsos positivos. Eles calcularam que, dado o volume de testes realizados por pesquisadores ao longo do tempo, um fator precisaria ter t-statistic acima de 3,0 — não mais 2,0 — para ser considerado estatisticamente robusto.")
    fala(doc, "Bailey e López de Prado formalizaram isso no conceito de Probability of Backtest Overfitting, ou PBO: a probabilidade de que o melhor resultado em testes de amostra seja o pior em dados fora da amostra. Eles demonstraram que, com combinatorial purged cross-validation, é possível estimar essa probabilidade diretamente.")
    fala(doc, "E Marcos López de Prado, no livro Advances in Financial Machine Learning de 2018, introduziu o Deflated Sharpe Ratio, ou DSR: uma versão do Sharpe que penaliza pela quantidade de estratégias testadas e pela não-normalidade dos retornos.")

    div(doc)
    h2(doc, "1.2 — As Três Fontes de Viés em Backtests")
    acao(doc, "Slide 2. Enumerate os três vieses, pausando em cada um.")
    fala(doc, "Existem três grandes fontes de viés que precisamos entender e controlar.")
    fala(doc, "Primeiro: Look-ahead bias, ou viés de antecipação. Ocorre quando você usa informação que não estaria disponível no momento da decisão de investimento. O exemplo mais comum: usar o retorno do mês T para construir o sinal do mês T. Na prática, você só sabe o retorno de T ao final de T — então o sinal só pode ser formado no início de T+1. No nosso código, controlamos isso com shift(1) no backtest.")
    fala(doc, "Segundo: Survivorship bias, ou viés de sobrevivência. Ocorre quando você testa sua estratégia somente em ativos que ainda existem hoje. Empresas que faliram, saíram do índice, foram incorporadas — essas não aparecem na sua amostra atual. O efeito é que você superestima o retorno histórico porque você só viu os 'sobreviventes'.")
    fala(doc, "Terceiro: Multiple testing bias, ou viés de múltiplos testes. Já falamos sobre isso. Se você testa 100 variações de um parâmetro e 5 funcionam bem, espera-se que, com 95% de confiança, 5 funcionem por acaso puro — mesmo que o verdadeiro efeito seja zero. A solução é aplicar correções estatísticas, como Bonferroni ou, mais adequado para séries financeiras, o ajuste proposto por Bailey e López de Prado.")

    div(doc)
    h2(doc, "1.3 — Walk-Forward Analysis vs In-Sample/Out-of-Sample")
    acao(doc, "Slide 3. Diagrama temporal na tela.")
    fala(doc, "A metodologia padrão em quant finance para mitigar look-ahead bias em otimização de parâmetros é o Walk-Forward Analysis.")
    fala(doc, "A ideia é simples: você divide a série temporal em janelas. Em cada janela, você tem um período de treinamento — in-sample — e um período de teste — out-of-sample. Você treina no in-sample, testa no out-of-sample, avança a janela, e repete.")
    fala(doc, "O resultado final é a concatenação dos períodos out-of-sample. Isso garante que cada predição foi feita com parâmetros calculados exclusivamente com dados disponíveis naquele momento.")
    fala(doc, "No nosso contexto, implementamos isso com a função backtest_walkforward que vocês já construíram. Ela usa 36 meses de treinamento e 6 meses de teste, avançando de 6 em 6. Os retornos líquidos finais são puramente out-of-sample.")
    fala(doc, "Uma variante mais sofisticada é o Purged Cross-Validation proposto por López de Prado: além de separar treino e teste, você remove um gap temporal entre eles — chamado 'embargo' — para eliminar qualquer vazamento de informação por sobreposição de retornos calculados em janelas adjacentes.")

    div(doc)
    h2(doc, "1.4 — Deflated Sharpe Ratio (DSR)")
    acao(doc, "Slide 4. Equação do DSR na tela.")
    fala(doc, "O Sharpe Ratio que calculamos nas aulas anteriores é o Sharpe observado: retorno médio dividido pelo desvio padrão, anualizado. É uma estatística pontual — não considera incerteza, não considera quantas estratégias testamos.")
    fala(doc, "O Deflated Sharpe Ratio corrige duas distorções: a inflação por múltiplos testes e o viés por não-normalidade.")
    fala(doc, "A fórmula envolve o Expected Maximum Sharpe Ratio, que cresce com o número de estratégias testadas. Quanto mais estratégias você testou, maior o Sharpe esperado por acaso puro — e portanto mais alto precisa ser o Sharpe observado para ser considerado genuíno.")
    fala(doc, "O DSR também corrige para skewness e kurtosis dos retornos. Retornos com cauda pesada ou assimetria negativa inflariam o Sharpe clássico — o DSR desconta isso.")
    fala(doc, "Hoje vamos implementar uma versão simplificada do DSR que captura a essência do conceito: penalização pelo número de configurações de janela testadas no walk-forward e ajuste por skewness e kurtosis.")

    div(doc)

    # =========================================================
    h1(doc, "PARTE 2 — CODIGO: BACKTEST_WALKFORWARD E VALIDACAO")
    tempo(doc, "0:35 – 1:30")
    div(doc)

    h2(doc, "2.1 — Setup Inicial")
    acao(doc, "Abrir Jupyter. Novo notebook: aula_08_backtest_rigoroso.ipynb.")
    fala(doc, "Vamos abrir o notebook da aula 8. Como sempre, começamos com os imports e carregamento de dados.")
    cod(doc, "import pandas as pd")
    cod(doc, "import numpy as np")
    cod(doc, "import matplotlib.pyplot as plt")
    cod(doc, "import matplotlib.gridspec as gridspec")
    cod(doc, "from scipy import stats")
    cod(doc, "import warnings")
    cod(doc, "warnings.filterwarnings('ignore')")
    cod(doc, "")
    cod(doc, "ret_mensais   = pd.read_parquet('../dados/retornos_mensais_limpo.parquet')")
    cod(doc, "sinal_v2      = pd.read_parquet('../dados/sinal_v2.parquet')")
    cod(doc, "pesos_v2      = pd.read_parquet('../dados/pesos_v2.parquet')")
    cod(doc, "ret_carteira  = pd.read_parquet('../dados/retorno_carteira.parquet')")
    cod(doc, "")
    cod(doc, "print(ret_mensais.shape, sinal_v2.shape)")
    fala(doc, "Carregamos os dados de todas as aulas anteriores. Agora vamos olhar o que já temos de out-of-sample no ret_carteira — este é o nosso benchmark de comparação.")

    div(doc)
    h2(doc, "2.2 — Função calcular_dsr()")
    acao(doc, "Digitar ao vivo. Explicar cada parâmetro.")
    fala(doc, "Antes de rodar o walk-forward, vamos implementar o DSR — assim já podemos aplicá-lo ao resultado.")
    cod(doc, "def calcular_dsr(retornos, n_estrategias=1):")
    cod(doc, "    '''")
    cod(doc, "    Deflated Sharpe Ratio (Bailey & Lopez de Prado, 2014).")
    cod(doc, "    Penaliza o Sharpe por multiplos testes e nao-normalidade.")
    cod(doc, "    '''")
    cod(doc, "    n  = len(retornos)")
    cod(doc, "    sr = retornos.mean() / retornos.std() * np.sqrt(12)")
    cod(doc, "    sk = retornos.skew()")
    cod(doc, "    ku = retornos.kurtosis()")
    cod(doc, "")
    cod(doc, "    # Expected max SR de n_estrategias tentativas (aprox. Extreme Value)")
    cod(doc, "    e_maxsr = np.sqrt(2) * stats.norm.ppf(1 - 1/n_estrategias) if n_estrategias > 1 else 0")
    cod(doc, "")
    cod(doc, "    # Correcao por nao-normalidade")
    cod(doc, "    sr_corr = sr * (1 - sk/6 * sr + (ku-3)/24 * sr**2)**(-0.5)")
    cod(doc, "")
    cod(doc, "    # Probabilidade de superar o expected max SR")
    cod(doc, "    dsr = stats.norm.cdf((sr_corr - e_maxsr) * np.sqrt(n - 1) /")
    cod(doc, "                         np.sqrt(1 - sr_corr * e_maxsr + sr_corr**2 * (ku-1)/4))")
    cod(doc, "    return {'sharpe_obs': sr, 'sharpe_corr': sr_corr, 'e_maxsr': e_maxsr, 'dsr': dsr}")
    fala(doc, "O retorno é um dicionário com quatro valores: o Sharpe observado, o Sharpe corrigido por não-normalidade, o Sharpe máximo esperado por acaso dado o número de estratégias testadas, e o DSR — que é uma probabilidade entre 0 e 1.")
    fala(doc, "Um DSR acima de 0,95 indica que o resultado é estatisticamente robusto mesmo após deflação. Abaixo de 0,5 levanta forte suspeita de overfitting.")

    div(doc)
    h2(doc, "2.3 — Função backtest_walkforward()")
    acao(doc, "Digitar ao vivo. Esta é a função central da aula.")
    fala(doc, "Agora a função de walk-forward. Ela recebe o sinal e os retornos mensais, e produz retornos puramente out-of-sample.")
    cod(doc, "def backtest_walkforward(sinal, ret_mensais, janela_treino=36, janela_teste=6):")
    cod(doc, "    '''")
    cod(doc, "    Walk-forward analysis.")
    cod(doc, "    janela_treino: meses de treinamento para otimizacao de parametros")
    cod(doc, "    janela_teste:  meses de avaliacao out-of-sample")
    cod(doc, "    '''")
    cod(doc, "    datas = sinal.index.sort_values()")
    cod(doc, "    resultados = []")
    cod(doc, "")
    cod(doc, "    inicio = janela_treino")
    cod(doc, "    while inicio + janela_teste <= len(datas):")
    cod(doc, "        treino_end = datas[inicio - 1]")
    cod(doc, "        teste_end  = datas[min(inicio + janela_teste - 1, len(datas)-1)]")
    cod(doc, "        ")
    cod(doc, "        # Periodo out-of-sample")
    cod(doc, "        datas_oos = datas[inicio:inicio + janela_teste]")
    cod(doc, "        ")
    cod(doc, "        for data in datas_oos:")
    cod(doc, "            if data in sinal.index:")
    cod(doc, "                sig = sinal.loc[data].dropna()")
    cod(doc, "                if len(sig) > 0:")
    cod(doc, "                    ranks  = sig.rank(ascending=False)")
    cod(doc, "                    n_long = max(int(len(ranks) * 0.2), 1)")
    cod(doc, "                    top    = ranks[ranks <= n_long].index")
    cod(doc, "                    pesos  = pd.Series(1/len(top), index=top)")
    cod(doc, "                    ")
    cod(doc, "                    if data in ret_mensais.index:")
    cod(doc, "                        ret_mes = ret_mensais.loc[data, pesos.index].dropna()")
    cod(doc, "                        pesos_  = pesos.reindex(ret_mes.index).dropna()")
    cod(doc, "                        pesos_ /= pesos_.sum()")
    cod(doc, "                        ret_oos = (ret_mes * pesos_).sum()")
    cod(doc, "                        resultados.append({'data': data, 'retorno': ret_oos, 'n_ativos': len(top)})")
    cod(doc, "        inicio += janela_teste")
    cod(doc, "    ")
    cod(doc, "    return pd.DataFrame(resultados).set_index('data')['retorno']")
    fala(doc, "Notem que dentro do loop só usamos dados até treino_end para qualquer decisão de parâmetros — aqui, nossos parâmetros são fixos, mas a estrutura permite variar o n_long, o lookback, qualquer hiperparâmetro. A decisão final de portfólio usa apenas o sinal daquele mês específico, sem vazamento.")

    div(doc)
    h2(doc, "2.4 — Executar Walk-Forward e Comparar")
    acao(doc, "Rodar a função. Pode demorar alguns segundos.")
    fala(doc, "Vamos rodar e comparar o resultado out-of-sample com o backtest simples.")
    cod(doc, "ret_oos = backtest_walkforward(sinal_v2, ret_mensais, janela_treino=36, janela_teste=6)")
    cod(doc, "print(f'Periodo OOS: {ret_oos.index.min()} a {ret_oos.index.max()}')")
    cod(doc, "print(f'Observacoes OOS: {len(ret_oos)}')")
    cod(doc, "")
    cod(doc, "# Calcular metricas do OOS")
    cod(doc, "sharpe_oos = ret_oos.mean() / ret_oos.std() * np.sqrt(12)")
    cod(doc, "cagr_oos   = (1 + ret_oos).prod() ** (12/len(ret_oos)) - 1")
    cod(doc, "")
    cod(doc, "print(f'Sharpe OOS: {sharpe_oos:.2f}')")
    cod(doc, "print(f'CAGR OOS:   {cagr_oos:.1%}')")
    fala(doc, "Espera-se que o Sharpe OOS seja um pouco menor que o in-sample — isso é normal e desejável. Significa que o modelo não está inflado. Se o OOS for igual ou maior que o in-sample, pode ser sinal de que a janela de teste é muito curta ou que você teve sorte específica.")

    div(doc)
    h2(doc, "2.5 — Aplicar o DSR")
    acao(doc, "Digitar. Mostrar como interpretar o resultado.")
    fala(doc, "Agora aplicamos o DSR. Como testamos poucas configurações — basicamente fixamos os parâmetros nas aulas anteriores —, vamos usar n_estrategias=5 como estimativa conservadora.")
    cod(doc, "dsr_result = calcular_dsr(ret_oos, n_estrategias=5)")
    cod(doc, "print('=== Deflated Sharpe Ratio ===')")
    cod(doc, "print(f'  Sharpe Observado:  {dsr_result[\"sharpe_obs\"]:.3f}')")
    cod(doc, "print(f'  Sharpe Corrigido:  {dsr_result[\"sharpe_corr\"]:.3f}')")
    cod(doc, "print(f'  E[MaxSR] esperado: {dsr_result[\"e_maxsr\"]:.3f}')")
    cod(doc, "print(f'  DSR (prob):        {dsr_result[\"dsr\"]:.3f}')")
    fala(doc, "O DSR próximo de 1 significa alta confiança de que o resultado não é artefato de overfitting. O DSR próximo de 0 seria um sinal de alerta. Para o Desafio Itaú, qualquer estratégia que vocês apresentarem deve ter DSR acima de 0,80 para ser considerada robusta.")

    div(doc)
    h2(doc, "2.6 — Visualizacao: In-Sample vs Out-of-Sample")
    acao(doc, "Gráfico comparativo. Mostrar divergência ou convergência.")
    fala(doc, "Vamos fazer um gráfico que mostra lado a lado o retorno acumulado in-sample e out-of-sample.")
    cod(doc, "fig, axes = plt.subplots(1, 2, figsize=(14, 5))")
    cod(doc, "")
    cod(doc, "# Acumulado")
    cod(doc, "ax1 = axes[0]")
    cod(doc, "ret_is  = ret_carteira.squeeze().dropna()")
    cod(doc, "cum_is  = (1 + ret_is).cumprod()")
    cod(doc, "cum_oos = (1 + ret_oos).cumprod()")
    cod(doc, "")
    cod(doc, "ax1.plot(cum_is.index,  cum_is.values,  label='In-Sample (backtest simples)',  color='#1A6EAE', lw=2)")
    cod(doc, "ax1.plot(cum_oos.index, cum_oos.values, label='Out-of-Sample (walk-forward)', color='#F5A623', lw=2, ls='--')")
    cod(doc, "ax1.set_title('Retorno Acumulado: IS vs OOS')")
    cod(doc, "ax1.legend(fontsize=9)")
    cod(doc, "ax1.grid(alpha=0.3)")
    cod(doc, "")
    cod(doc, "# Distribuicao de retornos mensais")
    cod(doc, "ax2 = axes[1]")
    cod(doc, "ax2.hist(ret_is,  bins=30, alpha=0.5, label='In-Sample',      color='#1A6EAE')")
    cod(doc, "ax2.hist(ret_oos, bins=30, alpha=0.5, label='Out-of-Sample', color='#F5A623')")
    cod(doc, "ax2.axvline(ret_is.mean(),  color='#1A6EAE', lw=2, ls='--')")
    cod(doc, "ax2.axvline(ret_oos.mean(), color='#F5A623', lw=2, ls='--')")
    cod(doc, "ax2.set_title('Distribuicao de Retornos Mensais')")
    cod(doc, "ax2.legend(fontsize=9)")
    cod(doc, "ax2.grid(alpha=0.3)")
    cod(doc, "")
    cod(doc, "plt.suptitle('Validacao Out-of-Sample — Sinal v2 com Walk-Forward', fontweight='bold')")
    cod(doc, "plt.tight_layout()")
    cod(doc, "plt.savefig('validacao_oos.png', dpi=150, bbox_inches='tight')")
    cod(doc, "plt.show()")
    fala(doc, "Se as curvas forem similares, ótimo — o sinal é robusto. Se o OOS cair muito em relação ao IS, precisamos investigar se há overfitting ou se o regime de mercado mudou.")

    div(doc)
    h2(doc, "2.7 — Salvar Retornos OOS")
    acao(doc, "Última célula.")
    fala(doc, "Salvamos o resultado como parquet para usar no relatório final.")
    cod(doc, "ret_oos.to_frame('retorno').to_parquet('../dados/retorno_walkforward_liquido.parquet')")
    cod(doc, "print('Salvo: retorno_walkforward_liquido.parquet')")

    div(doc)
    h2(doc, "2.8 — Recap e Proxima Aula")
    tempo(doc, "1:30 – 1:40")
    acao(doc, "Fechar notebook. Slide de fechamento.")
    fala(doc, "Hoje vocês aprenderam a diferença entre um backtest ingênuo e um backtest rigoroso. Implementaram walk-forward analysis para garantir que cada retorno é genuinamente out-of-sample. Calcularam o Deflated Sharpe Ratio para medir a robustez estatística do sinal.")
    fala(doc, "Na próxima aula — Aula 9 — vamos integrar uma LLM via API da Anthropic para gerar narrativas automáticas dos resultados e otimizar parâmetros com assist de GenAI. Preparem o access token da API — vou disponibilizar no grupo do WhatsApp.")
    fala(doc, "Até semana que vem!")

    folder = os.path.join(BASE, "aula-08-backtest-rigoroso")
    os.makedirs(folder, exist_ok=True)
    out = os.path.join(folder, "roteiro-aula-08-backtest-rigoroso.docx")
    doc.save(out)
    print(f"  Aula 08: roteiro salvo -> aula-08-backtest-rigoroso/")


def aula09():
    doc = novo_doc(9, "GenAI e LLMs no Pipeline Quant")

    # =========================================================
    h1(doc, "PARTE 1 — TEORIA: LARGE LANGUAGE MODELS NO CONTEXTO QUANT")
    tempo(doc, "0:00 – 0:25")
    div(doc)

    h2(doc, "1.1 — O que sao LLMs e como se conectam a Finance Quantitativa")
    acao(doc, "Slide 1. Tom entusiasmado — esta aula diferencia o curso.")
    fala(doc, "Bem-vindos à Aula 9! Essa é a aula mais diferente do curso — vamos sair da análise puramente quantitativa e integrar inteligência artificial generativa ao nosso pipeline.")
    fala(doc, "Large Language Models são modelos de linguagem de grande escala treinados em enormes volumes de texto. Claude, GPT, Gemini — são todos LLMs. Eles aprendem padrões estatísticos da linguagem humana e conseguem gerar texto coerente, responder perguntas, e — mais importante para nós — processar dados estruturados e produzir análises narrativas.")
    fala(doc, "No contexto quant, LLMs têm três usos principais. Primeiro: análise de sentimento em documentos financeiros — relatórios de earnings, atas do COPOM, releases de resultado. Segundo: geração automática de narrativas de performance — o modelo lê as métricas e escreve um comentário de gestor. Terceiro: assistência na geração de código e hipóteses — você descreve um sinal e o modelo ajuda a implementar.")
    fala(doc, "Hoje vamos explorar os dois últimos: geração de narrativa e assistência a código.")

    div(doc)
    h2(doc, "1.2 — Anatomia de uma API de LLM")
    acao(doc, "Slide 2. Diagrama de request/response.")
    fala(doc, "Para usar um LLM programaticamente, você faz chamadas a uma API. A Anthropic, criadora do Claude, oferece uma API REST que aceita mensagens e retorna respostas. O SDK Python simplifica isso em duas linhas.")
    fala(doc, "O conceito central é o de 'mensagem'. Você envia uma lista de mensagens com papel — 'user' ou 'assistant' — e conteúdo. O modelo responde com uma mensagem de assistant. Você pode incluir contexto longo no 'system prompt' — instruções de comportamento que valem para toda a conversa.")
    fala(doc, "Dois parâmetros importantes: temperature controla a aleatoriedade da resposta — 0 para determinístico, 1 para mais criativo. max_tokens limita o tamanho da resposta. Para análises financeiras, usamos temperature próxima de 0 para respostas mais factuais.")
    fala(doc, "O modelo que vamos usar hoje é o Claude Haiku — mais rápido e barato, adequado para experimentação. Para produção, o Claude Sonnet ou Opus oferece qualidade superior.")

    div(doc)
    h2(doc, "1.3 — Prompt Engineering para Analise Quantitativa")
    acao(doc, "Slide 3. Exemplos de prompts bons vs ruins.")
    fala(doc, "A qualidade da saída de um LLM depende diretamente da qualidade do prompt. Isso é chamado de prompt engineering.")
    fala(doc, "Um prompt ruim: 'Analise minha estratégia.' — vago, sem contexto, gera resposta genérica.")
    fala(doc, "Um prompt bom fornece: contexto específico — 'Esta é uma estratégia long-only de momentum cross-sectional no IBOVESPA'. Dados estruturados — métricas em formato legível. Instruções precisas — 'Escreva um parágrafo de 150 palavras no estilo de relatório de gestora institucional'. Formato esperado — 'Use linguagem técnica mas acessível, evite jargões excessivos'.")
    fala(doc, "Para dados financeiros, a técnica mais eficaz é fornecer os números diretamente no prompt — Sharpe, CAGR, drawdown — e pedir ao modelo que os interprete. O modelo não tem acesso à internet e não sabe os dados em tempo real, mas consegue raciocinar muito bem sobre dados que você fornece.")

    div(doc)

    # =========================================================
    h1(doc, "PARTE 2 — CODIGO: INTEGRANDO CLAUDE API AO PIPELINE")
    tempo(doc, "0:25 – 1:30")
    div(doc)

    h2(doc, "2.1 — Instalacao e Setup")
    acao(doc, "Novo notebook: aula_09_genai_pipeline.ipynb")
    fala(doc, "Primeiro, instalamos o SDK da Anthropic.")
    cod(doc, "# No terminal:")
    cod(doc, "# pip install anthropic")
    cod(doc, "")
    cod(doc, "import anthropic")
    cod(doc, "import pandas as pd")
    cod(doc, "import numpy as np")
    cod(doc, "import os")
    fala(doc, "A API key da Anthropic deve ser configurada como variável de ambiente. Nunca coloque chaves diretamente no código — elas podem vazar se você subir o notebook para o GitHub.")
    cod(doc, "# Configure no terminal antes de abrir o Jupyter:")
    cod(doc, "# set ANTHROPIC_API_KEY=sua-chave-aqui   (Windows)")
    cod(doc, "# export ANTHROPIC_API_KEY=sua-chave-aqui (Mac/Linux)")
    cod(doc, "")
    cod(doc, "client = anthropic.Anthropic()  # Le ANTHROPIC_API_KEY automaticamente")
    cod(doc, "print('Cliente Anthropic inicializado.')")

    div(doc)
    h2(doc, "2.2 — Primeira Chamada: Teste de Conectividade")
    acao(doc, "Digitar ao vivo. Mostrar a resposta do modelo.")
    fala(doc, "Vamos fazer uma chamada simples para verificar que tudo funciona.")
    cod(doc, "def chamar_claude(prompt_usuario, system_prompt='', modelo='claude-haiku-4-5-20251001', temperatura=0.0):")
    cod(doc, "    mensagem = client.messages.create(")
    cod(doc, "        model=modelo,")
    cod(doc, "        max_tokens=1024,")
    cod(doc, "        temperature=temperatura,")
    cod(doc, "        system=system_prompt,")
    cod(doc, "        messages=[{'role': 'user', 'content': prompt_usuario}]")
    cod(doc, "    )")
    cod(doc, "    return mensagem.content[0].text")
    cod(doc, "")
    cod(doc, "# Teste rapido")
    cod(doc, "resp = chamar_claude('O que e momentum em financas quantitativas? Responda em 3 frases.')")
    cod(doc, "print(resp)")
    fala(doc, "O modelo deve responder com uma explicação concisa sobre momentum. Se der erro de autenticação, verifique a API key. Se der erro de quota, falem comigo — vou fornecer uma chave de teste.")

    div(doc)
    h2(doc, "2.3 — Carregar Metricas da Estrategia")
    acao(doc, "Digitar. Construir o contexto de métricas.")
    fala(doc, "Agora vamos carregar os resultados do pipeline e montar um contexto rico para o modelo.")
    cod(doc, "ret_oos = pd.read_parquet('../dados/retorno_walkforward_liquido.parquet').squeeze()")
    cod(doc, "ret_is  = pd.read_parquet('../dados/retorno_carteira.parquet').squeeze()")
    cod(doc, "")
    cod(doc, "def resumo_metricas(retornos, nome='Estrategia'):")
    cod(doc, "    r = retornos.dropna()")
    cod(doc, "    sharpe = r.mean() / r.std() * np.sqrt(12)")
    cod(doc, "    cagr   = (1 + r).prod() ** (12/len(r)) - 1")
    cod(doc, "    vol    = r.std() * np.sqrt(12)")
    cod(doc, "    cum    = (1 + r).cumprod()")
    cod(doc, "    mdd    = (cum / cum.cummax() - 1).min()")
    cod(doc, "    return {")
    cod(doc, "        'nome': nome,")
    cod(doc, "        'periodo': f'{r.index.min().date()} a {r.index.max().date()}',")
    cod(doc, "        'sharpe': f'{sharpe:.2f}',")
    cod(doc, "        'cagr': f'{cagr:.1%}',")
    cod(doc, "        'vol_anual': f'{vol:.1%}',")
    cod(doc, "        'max_drawdown': f'{mdd:.1%}',")
    cod(doc, "        'n_meses': len(r)")
    cod(doc, "    }")
    cod(doc, "")
    cod(doc, "m_is  = resumo_metricas(ret_is,  'Backtest In-Sample')")
    cod(doc, "m_oos = resumo_metricas(ret_oos, 'Walk-Forward Out-of-Sample')")
    cod(doc, "print(m_is)")
    cod(doc, "print(m_oos)")

    div(doc)
    h2(doc, "2.4 — Gerar Narrativa de Performance com Claude")
    acao(doc, "Digitar ao vivo. Este é o ponto alto da aula.")
    fala(doc, "Agora montamos o prompt com as métricas e pedimos ao modelo que escreva um comentário de performance como uma gestora institucional faria.")
    cod(doc, "def gerar_comentario_performance(m_is, m_oos):")
    cod(doc, "    system = '''Voce e um analista quantitativo senior de uma gestora brasileira.")
    cod(doc, "    Seu estilo e tecnico, preciso, em portugues formal, sem exageros.")
    cod(doc, "    Quando afirmar algo sobre os dados, cite os numeros exatos fornecidos.")
    cod(doc, "    Tamanho: 200-250 palavras.'''")
    cod(doc, "")
    cod(doc, "    prompt = f'''Analise a performance da seguinte estrategia de momentum cross-sectional no IBOVESPA.")
    cod(doc, "")
    cod(doc, "RESULTADOS IN-SAMPLE ({m_is['periodo']}):")
    cod(doc, "- Sharpe Ratio: {m_is['sharpe']}")
    cod(doc, "- CAGR: {m_is['cagr']}")
    cod(doc, "- Volatilidade Anual: {m_is['vol_anual']}")
    cod(doc, "- Max Drawdown: {m_is['max_drawdown']}")
    cod(doc, "- Meses analisados: {m_is['n_meses']}")
    cod(doc, "")
    cod(doc, "RESULTADOS OUT-OF-SAMPLE — Walk-Forward ({m_oos['periodo']}):")
    cod(doc, "- Sharpe Ratio: {m_oos['sharpe']}")
    cod(doc, "- CAGR: {m_oos['cagr']}")
    cod(doc, "- Volatilidade Anual: {m_oos['vol_anual']}")
    cod(doc, "- Max Drawdown: {m_oos['max_drawdown']}")
    cod(doc, "- Meses analisados: {m_oos['n_meses']}")
    cod(doc, "")
    cod(doc, "Escreva um comentario de performance que:")
    cod(doc, "1. Contextualize a metodologia (momentum cross-sectional, sinal 12-1 com ajuste de volatilidade)")
    cod(doc, "2. Interprete os resultados IS com rigor")
    cod(doc, "3. Compare IS com OOS e avalie robustez")
    cod(doc, "4. Aponte riscos e limitacoes")
    cod(doc, "5. Conclua com recomendacao para comite de investimentos'''")
    cod(doc, "")
    cod(doc, "    return chamar_claude(prompt, system_prompt=system)")
    cod(doc, "")
    cod(doc, "comentario = gerar_comentario_performance(m_is, m_oos)")
    cod(doc, "print(comentario)")
    fala(doc, "Leiam o que o modelo gerou. Notem que ele usa exatamente os números que fornecemos, interpreta a relação IS/OOS, e escreve no estilo de relatório institucional. Isso não substitui o analista — mas acelera muito a produção de conteúdo de alta qualidade.")

    div(doc)
    h2(doc, "2.5 — Gerar Sugestoes de Melhoria do Sinal")
    acao(doc, "Digitar. Mostrar uso de LLM como assistente de pesquisa.")
    fala(doc, "Um segundo uso muito prático: pedir ao modelo sugestões de melhorias baseadas na literatura.")
    cod(doc, "def sugerir_melhorias(m_oos):")
    cod(doc, "    system = '''Voce e um pesquisador de factor investing com profundo conhecimento")
    cod(doc, "    em literatura academica de quantitative finance.'''")
    cod(doc, "")
    cod(doc, "    prompt = f'''Nossa estrategia de momentum cross-sectional no IBOVESPA obteve:")
    cod(doc, "- Sharpe OOS: {m_oos['sharpe']}")
    cod(doc, "- Max Drawdown: {m_oos['max_drawdown']}")
    cod(doc, "")
    cod(doc, "Com base em literatura academica (Jegadeesh & Titman 1993, Moskowitz et al 2012,")
    cod(doc, "Asness et al 2013, Fama & French 2015), sugira 3 modificacoes especificas")
    cod(doc, "que poderiam melhorar o Sharpe ou reduzir o drawdown.")
    cod(doc, "Para cada sugestao: (a) cite o paper original, (b) explique o mecanismo,")
    cod(doc, "(c) descreva como implementar em Python com pandas.'''")
    cod(doc, "")
    cod(doc, "    return chamar_claude(prompt, system_prompt=system, temperatura=0.3)")
    cod(doc, "")
    cod(doc, "sugestoes = sugerir_melhorias(m_oos)")
    cod(doc, "print(sugestoes)")
    fala(doc, "Isso é assistência a pesquisa — o modelo atua como um co-pesquisador que conhece a literatura. As sugestões devem ser validadas e implementadas por vocês, mas é um ponto de partida muito mais rico do que uma busca no Google.")

    div(doc)
    h2(doc, "2.6 — Salvar Narrativa no Relatorio")
    acao(doc, "Última célula da aula.")
    fala(doc, "Salvamos a narrativa e as sugestões em arquivo de texto para incluir no relatório final.")
    cod(doc, "with open('narrativa_performance.txt', 'w', encoding='utf-8') as f:")
    cod(doc, "    f.write('=== COMENTARIO DE PERFORMANCE ===\\n\\n')")
    cod(doc, "    f.write(comentario)")
    cod(doc, "    f.write('\\n\\n=== SUGESTOES DE MELHORIA ===\\n\\n')")
    cod(doc, "    f.write(sugestoes)")
    cod(doc, "")
    cod(doc, "print('Narrativa salva em narrativa_performance.txt')")

    div(doc)
    h2(doc, "2.7 — Recap e Proxima Aula")
    tempo(doc, "1:30 – 1:40")
    acao(doc, "Fechar notebook. Slide final.")
    fala(doc, "Hoje vocês integraram uma LLM de ponta ao pipeline quant. Geraram narrativa de performance no estilo institucional e obtiveram sugestões de pesquisa baseadas em literatura acadêmica — tudo de forma programática.")
    fala(doc, "Na próxima e última aula — Aula 10 — vamos montar o relatório final completo, integrar todos os componentes, e fazer uma simulação da defesa para o Desafio Itaú. Tragam dúvidas, pensem em como vão apresentar a estratégia de vocês. Até semana que vem!")

    folder = os.path.join(BASE, "aula-09-genai")
    os.makedirs(folder, exist_ok=True)
    out = os.path.join(folder, "roteiro-aula-09-genai.docx")
    doc.save(out)
    print(f"  Aula 09: roteiro salvo -> aula-09-genai/")


def aula10():
    doc = novo_doc(10, "Relatorio Final e Simulacao de Defesa")

    # =========================================================
    h1(doc, "PARTE 1 — TEORIA: COMO APRESENTAR ESTRATEGIAS QUANTITATIVAS")
    tempo(doc, "0:00 – 0:20")
    div(doc)

    h2(doc, "1.1 — O que os Juizes do Desafio Itaú Avaliam")
    acao(doc, "Slide 1. Tom motivador — última aula, chegamos ao fim.")
    fala(doc, "Pessoal, chegamos à Aula 10 — a última do Intensivão Quant AI. Parabéns por terem chegado até aqui. Em 10 semanas, vocês construíram do zero um pipeline completo de gestão quantitativa de portfólios.")
    fala(doc, "Hoje temos dois objetivos: montar o relatório final completo e fazer uma simulação realista de como defender a estratégia perante os juízes do Desafio Itaú Asset Management.")
    fala(doc, "O que os juízes avaliam? Com base nas edições anteriores e nos critérios publicados, podemos identificar quatro dimensões principais.")
    fala(doc, "Primeira: rigor metodológico. O backtest foi conduzido sem viés? Walk-forward? Look-ahead controlado? Tratamento de custos de transação? Essa dimensão é eliminatória — sem rigor, a estratégia não passa.")
    fala(doc, "Segunda: fundamentação econômica. Por que o fator deveria funcionar? Qual o mecanismo econômico ou comportamental por trás do sinal? Citar Jegadeesh & Titman é bom — explicar por que momentum existe no mercado brasileiro é melhor ainda.")
    fala(doc, "Terceira: qualidade da implementação. O código é limpo, reproduzível, bem documentado? A pipeline funciona do zero com os parquets base? Há controle de versão?")
    fala(doc, "Quarta: comunicação dos resultados. A apresentação é clara, os gráficos são legíveis, as conclusões são proporcionais à evidência? Um resultado honesto com limitações bem articuladas é muito mais valioso que um resultado exagerado.")

    div(doc)
    h2(doc, "1.2 — Estrutura do Relatorio Final")
    acao(doc, "Slide 2. Sumário do relatório.")
    fala(doc, "O relatório final deve ter a seguinte estrutura.")
    fala(doc, "Seção 1: Sumário Executivo — uma página. Hipótese, metodologia, resultado principal, limitações. Um juiz ocupado deve conseguir entender tudo em 2 minutos.")
    fala(doc, "Seção 2: Dados e Universo de Investimentos — de onde vêm os dados, qual o período, quantos ativos, como foi feita a limpeza. Seja específico: cite o yfinance, o IBOVESPA, o período de 2015 a 2024.")
    fala(doc, "Seção 3: Metodologia — descreva o sinal em linguagem matemática e intuição econômica. Descreva o processo de construção de portfólio. Descreva o backtest e as salvaguardas de rigor.")
    fala(doc, "Seção 4: Resultados — apresente as métricas IS e OOS lado a lado. Gráficos de equity curve, distribuição de retornos, drawdowns. IC médio. DSR.")
    fala(doc, "Seção 5: Análise de Sensibilidade — o que acontece se você mudar o lookback de 12 para 9 ou 15 meses? Se mudar o portfólio de top 20% para top 10%? Resultados robustos não mudam dramaticamente com pequenas variações de parâmetros.")
    fala(doc, "Seção 6: Limitações e Trabalhos Futuros — seja honesto. Survivorship bias, custos de transação aproximados, período limitado, regime de mercado único. Isso mostra maturidade intelectual.")
    fala(doc, "Seção 7: Referências — cite os papers acadêmicos corretamente.")

    div(doc)
    h2(doc, "1.3 — Como Defender sob Pressao")
    acao(doc, "Slide 3. Simulação de perguntas difíceis.")
    fala(doc, "Os juízes vão fazer perguntas difíceis. Vou simular algumas que vocês precisam estar preparados para responder.")
    fala(doc, "Pergunta: 'O resultado de vocês é atribuível ao fator momentum ou ao beta de mercado?' — Resposta esperada: comparar a correlação da estratégia com o IBOVESPA, mostrar o alpha de Jensen ou um information ratio.")
    fala(doc, "Pergunta: 'Como vocês controlaram survivorship bias?' — Resposta: reconhecer a limitação, explicar que o yfinance com composição histórica do índice minimiza mas não elimina o problema, citar que isso é uma limitação declarada na seção 6.")
    fala(doc, "Pergunta: 'Qual seria a capacidade da estratégia em termos de AUM?' — Resposta: estimar a liquidez média dos ativos do portfólio, calcular quantos reais poderiam ser gerenciados sem impacto de mercado significativo.")
    fala(doc, "Pergunta: 'Você adicionaria outros fatores?' — Resposta: mencionar value, quality, low vol — descrever como um modelo multifator funcionaria e citar Fama & French 1993.")
    fala(doc, "A regra de ouro na defesa: nunca finja saber o que não sabe. 'Excelente pergunta, não testamos isso, mas hipotetizamos que...' é muito melhor do que uma resposta incorreta com confiança falsa.")

    div(doc)

    # =========================================================
    h1(doc, "PARTE 2 — CODIGO: MONTAR O RELATORIO FINAL")
    tempo(doc, "0:20 – 1:20")
    div(doc)

    h2(doc, "2.1 — Setup: Carregar Todos os Dados do Pipeline")
    acao(doc, "Novo notebook: aula_10_relatorio_final.ipynb")
    fala(doc, "Vamos carregar todos os artefatos que produzimos nas 9 aulas anteriores e construir o relatório visual completo.")
    cod(doc, "import pandas as pd")
    cod(doc, "import numpy as np")
    cod(doc, "import matplotlib.pyplot as plt")
    cod(doc, "import matplotlib.gridspec as gridspec")
    cod(doc, "from scipy import stats")
    cod(doc, "import warnings")
    cod(doc, "warnings.filterwarnings('ignore')")
    cod(doc, "")
    cod(doc, "# Carregar todos os parquets do pipeline")
    cod(doc, "precos        = pd.read_parquet('../dados/precos_ibov.parquet')")
    cod(doc, "ret_diarios   = pd.read_parquet('../dados/retornos_diarios_limpo.parquet')")
    cod(doc, "ret_mensais   = pd.read_parquet('../dados/retornos_mensais_limpo.parquet')")
    cod(doc, "sinal_v1      = pd.read_parquet('../dados/sinal_v1.parquet')")
    cod(doc, "sinal_v2      = pd.read_parquet('../dados/sinal_v2.parquet')")
    cod(doc, "pesos_v1      = pd.read_parquet('../dados/pesos_v1.parquet')")
    cod(doc, "pesos_v2      = pd.read_parquet('../dados/pesos_v2.parquet')")
    cod(doc, "ret_carteira  = pd.read_parquet('../dados/retorno_carteira.parquet').squeeze()")
    cod(doc, "ret_oos       = pd.read_parquet('../dados/retorno_walkforward_liquido.parquet').squeeze()")
    cod(doc, "")
    cod(doc, "print('Pipeline completo carregado!')")
    cod(doc, "print(f'Periodo: {ret_mensais.index.min().date()} a {ret_mensais.index.max().date()}')")
    cod(doc, "print(f'Ativos:  {ret_mensais.shape[1]}')")

    div(doc)
    h2(doc, "2.2 — Calcular Metricas Completas")
    acao(doc, "Digitar. Função abrangente de métricas.")
    fala(doc, "Vamos criar uma função completa de métricas que usaremos em todo o relatório.")
    cod(doc, "def metricas_completas(retornos, nome='Estrategia', rf_anual=0.1025):")
    cod(doc, "    r  = retornos.dropna()")
    cod(doc, "    rf = (1 + rf_anual) ** (1/12) - 1  # CDI mensal aproximado")
    cod(doc, "    excesso = r - rf")
    cod(doc, "    ")
    cod(doc, "    sharpe    = excesso.mean() / excesso.std() * np.sqrt(12)")
    cod(doc, "    sortino   = excesso.mean() / excesso[excesso < 0].std() * np.sqrt(12)")
    cod(doc, "    cagr      = (1 + r).prod() ** (12/len(r)) - 1")
    cod(doc, "    vol       = r.std() * np.sqrt(12)")
    cod(doc, "    cum       = (1 + r).cumprod()")
    cod(doc, "    mdd       = (cum / cum.cummax() - 1).min()")
    cod(doc, "    calmar    = cagr / abs(mdd) if mdd != 0 else np.nan")
    cod(doc, "    skew      = r.skew()")
    cod(doc, "    kurt      = r.kurtosis()")
    cod(doc, "    win_rate  = (r > 0).mean()")
    cod(doc, "    ")
    cod(doc, "    return pd.Series({")
    cod(doc, "        'CAGR':              f'{cagr:.1%}',")
    cod(doc, "        'Vol Anual':         f'{vol:.1%}',")
    cod(doc, "        'Sharpe Ratio':      f'{sharpe:.2f}',")
    cod(doc, "        'Sortino Ratio':     f'{sortino:.2f}',")
    cod(doc, "        'Max Drawdown':      f'{mdd:.1%}',")
    cod(doc, "        'Calmar Ratio':      f'{calmar:.2f}',")
    cod(doc, "        'Skewness':          f'{skew:.2f}',")
    cod(doc, "        'Kurtosis':          f'{kurt:.2f}',")
    cod(doc, "        'Win Rate (mensal)': f'{win_rate:.1%}',")
    cod(doc, "        'N Meses':           len(r)")
    cod(doc, "    }, name=nome)")
    cod(doc, "")
    cod(doc, "m_is  = metricas_completas(ret_carteira, 'Backtest IS')")
    cod(doc, "m_oos = metricas_completas(ret_oos,      'Walk-Forward OOS')")
    cod(doc, "tabela = pd.DataFrame([m_is, m_oos]).T")
    cod(doc, "print(tabela.to_string())")

    div(doc)
    h2(doc, "2.3 — Painel Principal: Equity Curve e Metricas")
    acao(doc, "Digitar. O gráfico mais importante do relatório.")
    fala(doc, "Agora o painel principal — a figura que vai na primeira página do relatório.")
    cod(doc, "fig = plt.figure(figsize=(16, 10))")
    cod(doc, "gs  = gridspec.GridSpec(3, 3, figure=fig, hspace=0.4, wspace=0.35)")
    cod(doc, "")
    cod(doc, "# --- Equity curve ---")
    cod(doc, "ax_eq = fig.add_subplot(gs[0, :])")
    cod(doc, "cum_is  = (1 + ret_carteira.dropna()).cumprod()")
    cod(doc, "cum_oos = (1 + ret_oos.dropna()).cumprod()")
    cod(doc, "ax_eq.plot(cum_is,  label='Backtest In-Sample',      color='#1A6EAE', lw=2)")
    cod(doc, "ax_eq.plot(cum_oos, label='Walk-Forward OOS',        color='#F5A623', lw=2, ls='--')")
    cod(doc, "ax_eq.set_title('Retorno Acumulado da Estrategia Momentum v2', fontsize=13, fontweight='bold')")
    cod(doc, "ax_eq.legend(fontsize=10)")
    cod(doc, "ax_eq.grid(alpha=0.3)")
    cod(doc, "ax_eq.set_ylabel('Valor da Cota')")
    cod(doc, "")
    cod(doc, "# --- Drawdown ---")
    cod(doc, "ax_dd = fig.add_subplot(gs[1, :])")
    cod(doc, "dd_oos = (cum_oos / cum_oos.cummax() - 1)")
    cod(doc, "ax_dd.fill_between(dd_oos.index, dd_oos.values, 0, color='#E74C3C', alpha=0.5)")
    cod(doc, "ax_dd.set_title('Drawdown — Out-of-Sample', fontsize=11)")
    cod(doc, "ax_dd.set_ylabel('Drawdown')")
    cod(doc, "ax_dd.grid(alpha=0.3)")
    cod(doc, "")
    cod(doc, "# --- Retornos mensais bar chart ---")
    cod(doc, "ax_bar = fig.add_subplot(gs[2, :2])")
    cod(doc, "colors = ['#1E8B4C' if x > 0 else '#E74C3C' for x in ret_oos.values]")
    cod(doc, "ax_bar.bar(range(len(ret_oos)), ret_oos.values, color=colors, alpha=0.8)")
    cod(doc, "ax_bar.axhline(0, color='black', lw=0.8)")
    cod(doc, "ax_bar.set_title('Retornos Mensais OOS', fontsize=11)")
    cod(doc, "ax_bar.set_ylabel('Retorno Mensal')")
    cod(doc, "ax_bar.grid(alpha=0.2, axis='y')")
    cod(doc, "")
    cod(doc, "# --- QQ-plot ---")
    cod(doc, "ax_qq = fig.add_subplot(gs[2, 2])")
    cod(doc, "stats.probplot(ret_oos.dropna(), dist='norm', plot=ax_qq)")
    cod(doc, "ax_qq.set_title('QQ-Plot Retornos OOS', fontsize=11)")
    cod(doc, "ax_qq.grid(alpha=0.3)")
    cod(doc, "")
    cod(doc, "plt.suptitle('Relatorio Final — Estrategia Momentum IBOVESPA | Intensivao Quant AI',")
    cod(doc, "             fontsize=14, fontweight='bold', color='#0D1B3E')")
    cod(doc, "plt.savefig('painel_relatorio_final.png', dpi=150, bbox_inches='tight')")
    cod(doc, "plt.show()")
    fala(doc, "Este painel condensa toda a história da estratégia: performance acumulada, risco via drawdown, distribuição dos retornos mensais, e diagnóstico de normalidade. É a figura que abriria qualquer pitchbook institucional.")

    div(doc)
    h2(doc, "2.4 — Analise de Sensibilidade de Parametros")
    acao(doc, "Digitar. Mostrar robustez do sinal.")
    fala(doc, "Para demonstrar robustez, vamos testar o sinal com diferentes lookbacks e ver se o resultado se mantém.")
    cod(doc, "def backtest_simples(sinal, ret_mensais, n_long_pct=0.2):")
    cod(doc, "    retornos = []")
    cod(doc, "    for data in sinal.index:")
    cod(doc, "        sig = sinal.loc[data].dropna()")
    cod(doc, "        if len(sig) < 5: continue")
    cod(doc, "        ranks  = sig.rank(ascending=False)")
    cod(doc, "        n      = max(int(len(ranks) * n_long_pct), 1)")
    cod(doc, "        top    = ranks[ranks <= n].index")
    cod(doc, "        pesos  = pd.Series(1/len(top), index=top)")
    cod(doc, "        if data in ret_mensais.index:")
    cod(doc, "            ret_m = ret_mensais.loc[data, top].dropna()")
    cod(doc, "            pw    = pesos.reindex(ret_m.index).dropna()")
    cod(doc, "            pw   /= pw.sum()")
    cod(doc, "            retornos.append({'data': data, 'ret': (ret_m * pw).sum()})")
    cod(doc, "    return pd.DataFrame(retornos).set_index('data')['ret']")
    cod(doc, "")
    cod(doc, "# Testar lookbacks de 6 a 18 meses")
    cod(doc, "resultados_sensib = {}")
    cod(doc, "for lb in [6, 9, 12, 15, 18]:")
    cod(doc, "    sinal_lb = ret_mensais.shift(2).rolling(lb).sum()")
    cod(doc, "    ret_lb   = backtest_simples(sinal_lb, ret_mensais)")
    cod(doc, "    sharpe   = ret_lb.mean() / ret_lb.std() * np.sqrt(12)")
    cod(doc, "    resultados_sensib[f'Lookback {lb}m'] = round(sharpe, 2)")
    cod(doc, "")
    cod(doc, "print('Sensibilidade do Sharpe por Lookback:')")
    cod(doc, "for k, v in resultados_sensib.items():")
    cod(doc, "    print(f'  {k}: Sharpe = {v}')")
    fala(doc, "Se o Sharpe se mantiver relativamente estável entre 0,6 e 1,0 para todos os lookbacks, isso é sinal de robustez. Se só funcionar para lookback=12, levanta suspeita de overfitting.")

    div(doc)
    h2(doc, "2.5 — Gerar Tabela de Sensibilidade Grafico")
    acao(doc, "Digitar e mostrar.")
    cod(doc, "fig, axes = plt.subplots(1, 2, figsize=(12, 4))")
    cod(doc, "")
    cod(doc, "# Sharpe por lookback")
    cod(doc, "lbs    = list(resultados_sensib.keys())")
    cod(doc, "sharps = list(resultados_sensib.values())")
    cod(doc, "axes[0].bar(lbs, sharps, color='#1A6EAE', alpha=0.8)")
    cod(doc, "axes[0].axhline(0, color='black', lw=0.8)")
    cod(doc, "axes[0].set_title('Sharpe por Lookback do Sinal')")
    cod(doc, "axes[0].set_ylabel('Sharpe Ratio')")
    cod(doc, "axes[0].tick_params(axis='x', rotation=30)")
    cod(doc, "axes[0].grid(alpha=0.3, axis='y')")
    cod(doc, "")
    cod(doc, "# Sharpe por n_long_pct")
    cod(doc, "resultados_nlg = {}")
    cod(doc, "for pct in [0.10, 0.15, 0.20, 0.25, 0.30]:")
    cod(doc, "    sinal_fix = ret_mensais.shift(2).rolling(12).sum()")
    cod(doc, "    ret_fix   = backtest_simples(sinal_fix, ret_mensais, n_long_pct=pct)")
    cod(doc, "    resultados_nlg[f'Top {int(pct*100)}%'] = round(ret_fix.mean() / ret_fix.std() * np.sqrt(12), 2)")
    cod(doc, "")
    cod(doc, "pcts   = list(resultados_nlg.keys())")
    cod(doc, "sharps2 = list(resultados_nlg.values())")
    cod(doc, "axes[1].bar(pcts, sharps2, color='#F5A623', alpha=0.8)")
    cod(doc, "axes[1].axhline(0, color='black', lw=0.8)")
    cod(doc, "axes[1].set_title('Sharpe por Tamanho do Portfolio')")
    cod(doc, "axes[1].set_ylabel('Sharpe Ratio')")
    cod(doc, "axes[1].grid(alpha=0.3, axis='y')")
    cod(doc, "")
    cod(doc, "plt.suptitle('Analise de Sensibilidade de Parametros', fontweight='bold')")
    cod(doc, "plt.tight_layout()")
    cod(doc, "plt.savefig('sensibilidade_parametros.png', dpi=150, bbox_inches='tight')")
    cod(doc, "plt.show()")

    div(doc)
    h2(doc, "2.6 — IC Medio e Estabilidade Temporal")
    acao(doc, "Digitar. Mostrar a estabilidade preditiva do sinal ao longo do tempo.")
    fala(doc, "O IC médio nos diz se o sinal tem poder preditivo genuíno. Vamos calcular o IC mês a mês e plotar a série temporal.")
    cod(doc, "from scipy.stats import spearmanr")
    cod(doc, "")
    cod(doc, "ic_serie = []")
    cod(doc, "for i in range(1, len(sinal_v2.index)):")
    cod(doc, "    data_sinal  = sinal_v2.index[i-1]")
    cod(doc, "    data_ret    = sinal_v2.index[i]")
    cod(doc, "    if data_ret not in ret_mensais.index: continue")
    cod(doc, "    s = sinal_v2.loc[data_sinal].dropna()")
    cod(doc, "    r = ret_mensais.loc[data_ret, s.index].dropna()")
    cod(doc, "    s = s.reindex(r.index).dropna()")
    cod(doc, "    if len(s) > 10:")
    cod(doc, "        ic, _ = spearmanr(s, r)")
    cod(doc, "        ic_serie.append({'data': data_ret, 'ic': ic})")
    cod(doc, "")
    cod(doc, "ic_df = pd.DataFrame(ic_serie).set_index('data')")
    cod(doc, "ic_rolling = ic_df['ic'].rolling(12).mean()")
    cod(doc, "")
    cod(doc, "fig, axes = plt.subplots(2, 1, figsize=(12, 7), sharex=True)")
    cod(doc, "axes[0].bar(ic_df.index, ic_df['ic'].values, color=['#1E8B4C' if x>0 else '#E74C3C' for x in ic_df['ic']], alpha=0.6)")
    cod(doc, "axes[0].axhline(0, color='black', lw=0.8)")
    cod(doc, "axes[0].set_title(f'IC Mensal — Media: {ic_df[\"ic\"].mean():.3f}')")
    cod(doc, "axes[0].grid(alpha=0.3)")
    cod(doc, "")
    cod(doc, "axes[1].plot(ic_rolling.index, ic_rolling.values, color='#0D1B3E', lw=2)")
    cod(doc, "axes[1].axhline(0, color='black', lw=0.8)")
    cod(doc, "axes[1].set_title('IC Rolling 12 Meses')")
    cod(doc, "axes[1].grid(alpha=0.3)")
    cod(doc, "")
    cod(doc, "plt.suptitle('Information Coefficient — Sinal v2', fontweight='bold')")
    cod(doc, "plt.tight_layout()")
    cod(doc, "plt.savefig('ic_temporal.png', dpi=150, bbox_inches='tight')")
    cod(doc, "plt.show()")

    div(doc)

    # =========================================================
    h1(doc, "PARTE 3 — SIMULACAO DE DEFESA")
    tempo(doc, "1:20 – 1:40")
    div(doc)

    h2(doc, "3.1 — Estrutura da Apresentacao")
    acao(doc, "Fechar notebooks. Modo apresentação.")
    fala(doc, "Agora vamos simular a defesa. Cada grupo tem 10 minutos de apresentação e 5 minutos de perguntas. Vou fazer o papel dos juízes.")
    fala(doc, "Estrutura ideal da apresentação em 10 minutos: 1 minuto para introdução e hipótese — por que momentum? 2 minutos para dados e metodologia — o pipeline. 3 minutos para resultados — IS e OOS, com os gráficos do painel principal. 2 minutos para análise de sensibilidade e robustez. 2 minutos para limitações e trabalhos futuros.")
    fala(doc, "A primeira coisa que os juízes querem ouvir é a hipótese clara: 'Testamos a hipótese de que ações com maior retorno nos últimos 11 meses, excluindo o mês imediatamente anterior, continuam a superar nos meses seguintes — fenômeno documentado por Jegadeesh e Titman em 1993.' Isso prova que você sabe o que está fazendo e por quê.")

    div(doc)
    h2(doc, "3.2 — Perguntas Simuladas")
    acao(doc, "Fazer perguntas difíceis para os participantes. Deixar responderem antes de revelar a resposta ideal.")
    fala(doc, "Pergunta 1: 'Seu Sharpe OOS de X,XX é significativo? Qual o p-valor dessa estatística?'")
    fala(doc, "Resposta ideal: 'Com N meses de dados, o Sharpe de X,XX tem t-statistic de Sharpe vezes raiz de N, o que dá aproximadamente Y. Aplicando o DSR com N configurações testadas, obtemos probabilidade de Z de que o resultado não é overfitting.'")
    fala(doc, "Pergunta 2: 'Como a estratégia se comportou durante a crise da COVID?'")
    fala(doc, "Resposta ideal: 'Em março de 2020, a estratégia sofreu drawdown de X por cento — próximo do mercado, já que momentum tem correlação positiva com mercado em crises. Isso é consistente com a literatura — momentum crashs são documentados em crises de liquidez severas, como discutem Daniel e Moskowitz 2016.'")
    fala(doc, "Pergunta 3: 'Por que não usar alocação por Markowitz em vez de equal-weight?'")
    fala(doc, "Resposta ideal: 'Testamos ambas as abordagens. DeMiguel et al. 2009 mostram que a carteira de mínima variância raramente supera equal-weight fora da amostra. Em nosso teste, equal-weight produziu Sharpe de X versus Y do Markowitz, com muito menos instabilidade de pesos — o turnover do Markowitz foi Z por cento mais alto, gerando custos adicionais.'")

    div(doc)
    h2(doc, "3.3 — Fechamento do Intensivao")
    tempo(doc, "1:35 – 1:40")
    acao(doc, "Tom solene e motivador. Este é o encerramento do curso.")
    fala(doc, "Chegamos ao fim do Intensivão Quant AI. Em 10 semanas, vocês aprenderam a baixar e limpar dados financeiros de alta frequência, construir sinais quantitativos com fundamentação acadêmica, implementar backtests rigorosos com controle de look-ahead bias, aplicar diferentes metodologias de alocação de portfólios, conduzir validação out-of-sample com walk-forward analysis, medir a robustez estatística com o Deflated Sharpe Ratio, integrar Large Language Models ao pipeline quantitativo, e comunicar resultados no padrão de uma gestora institucional.")
    fala(doc, "O mercado de trabalho em finanças quantitativas no Brasil está em expansão acelerada. A Itaú Asset, a Verde, a Ibiuna, a Kadima, a Giant Steps — todas contratam pessoas com exatamente o perfil que vocês estão desenvolvendo. O Desafio Itaú é uma porta de entrada real para esse mundo.")
    fala(doc, "Mas independente do resultado da competição — o que vocês aprenderam aqui vai muito além de um troféu. Vocês construíram intuição quantitativa, que leva anos para desenvolver, em dois meses e meio. Isso é resultado do esforço de cada um de vocês.")
    fala(doc, "Da parte da Impact UFSCAR e da Diretoria Quant, obrigado pela confiança e pela dedicação. Boa sorte no Desafio. Façam bonito!")
    acao(doc, "Aplausos. Tirar foto do grupo para as redes sociais da Impact.")

    folder = os.path.join(BASE, "aula-10-relatorio-defesa")
    os.makedirs(folder, exist_ok=True)
    out = os.path.join(folder, "roteiro-aula-10-relatorio-defesa.docx")
    doc.save(out)
    print(f"  Aula 10: roteiro salvo -> aula-10-relatorio-defesa/")


if __name__ == "__main__":
    print("Gerando roteiros das aulas 08, 09, 10...")
    aula08()
    aula09()
    aula10()
    print("Concluido!")
